# Dependabot configuration for Rally extension
# Automatically checks for dependency updates and creates PRs

version: 2
updates:
  # Python dependencies (API)
  - package-ecosystem: "pip"
    directory: "/api-rally"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "NEI-maintainers"
    labels:
      - "dependencies"
      - "python"
      - "api"
    commit-message:
      prefix: "chore(api)"
      include: "scope"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]

  # npm dependencies (Web)
  - package-ecosystem: "npm"
    directory: "/web-rally"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "NEI-maintainers"
    labels:
      - "dependencies"
      - "javascript"
      - "web"
    commit-message:
      prefix: "chore(web)"
      include: "scope"
    ignore:
      # Ignore React major updates unless ready
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "NEI-maintainers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/api-rally"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "NEI-maintainers"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"

  - package-ecosystem: "docker"
    directory: "/web-rally"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "NEI-maintainers"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"

