version: "3.9"

services:
  web_nei:
    environment:
      ENABLE_RALLY: 'True'


  api_rally:
    build:
      context: extensions/rally/api-rally
    ports:
      - 8003:8003
    environment:
      POSTGRES_SERVER: db_pg
      POSTGRES_PASSWORD: postgres
      JWT_PUBLIC_KEY_PATH: /jwt.key.pub
    volumes:
      - ./extensions/rally/api-rally:/api_rally
      - ./dev-keys/jwt.key.pub:/jwt.key.pub:ro
    depends_on:
      db_pg:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  web_rally:
    build:
      context: extensions/rally/web-rally
    ports:
      - 3003:3003
    volumes:
      - rally_pnpm_store:/pnpm
      - ./extensions/rally/web-rally:/web_rally
      - rally_modules:/web_rally/node_modules
    networks:
      - frontend
    restart: unless-stopped

  proxy:
    volumes:
      - ./dev/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dev/proxy/locations.conf:/etc/nginx/conf.d/locations.conf:ro
      - ./dev/proxy/locations.rally.conf:/etc/nginx/conf.d/locations.rally.conf:ro
    depends_on:
      - api_rally
      - web_rally

volumes:
  rally_pnpm_store:
    driver: local
  rally_modules:
    driver: local
