version: "3.9"

services:
  web_nei:
    environment:
      ENABLE_GALA: 'True'

  api_rally:
    image: ghcr.io/nei-aauav/api-rally:${TAG:-latest}
    build:
      context: extensions/rally/api-rally
      dockerfile: Dockerfile.prod
    ports:
      - 8003:8003
    environment:
      ENV: production
      POSTGRES_SERVER: db_pg
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      JWT_PUBLIC_KEY_PATH: /jwt.key.pub
    volumes: 
      - /deploy/keys/jwt.key.pub:/jwt.key.pub:ro
      - /deploy/api-rally/static:/api_rally/static
    depends_on:
      db_pg:
        condition: service_healthy
    networks:
      - backend
    restart: always

  web_rally:
    image: ghcr.io/nei-aauav/web-rally:${TAG:-latest}
    build:
      context: extensions/rally
      dockerfile: web-rally/Dockerfile.prod
      # Multi-stage build handles: schema gen → web build → nginx serve
    ports:
      - 3003:3003
    networks:
      - frontend
    restart: always
