// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8003' | (string & {});
};

/**
 * ActivityCreate
 *
 * Schema for creating an activity
 */
export type ActivityCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Activity type enum
     */
    activity_type: ActivityType;
    /**
     * Checkpoint Id
     */
    checkpoint_id: number;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * ActivityListResponse
 *
 * Schema for activity list response
 */
export type ActivityListResponse = {
    /**
     * Activities
     */
    activities: Array<ActivityResponse>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Size
     */
    size: number;
};

/**
 * ActivityRanking
 *
 * Schema for activity-specific ranking
 */
export type ActivityRanking = {
    /**
     * Activity Id
     */
    activity_id: number;
    /**
     * Activity Name
     */
    activity_name: string;
    /**
     * Rankings
     */
    rankings: Array<TeamRanking>;
};

/**
 * ActivityResponse
 *
 * Schema for activity response
 */
export type ActivityResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Activity type enum
     */
    activity_type: ActivityType;
    /**
     * Checkpoint Id
     */
    checkpoint_id: number;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ActivityResultCreate
 *
 * Schema for creating an activity result
 */
export type ActivityResultCreate = {
    /**
     * Activity Id
     */
    activity_id: number;
    /**
     * Team Id
     */
    team_id: number;
    /**
     * Result Data
     */
    result_data?: {
        [key: string]: unknown;
    };
    /**
     * Extra Shots
     */
    extra_shots?: number;
    /**
     * Penalties
     */
    penalties?: {
        [key: string]: number;
    };
};

/**
 * ActivityResultEvaluation
 *
 * Schema for activity result evaluation (without team_id and activity_id)
 */
export type ActivityResultEvaluation = {
    /**
     * Result Data
     */
    result_data?: {
        [key: string]: unknown;
    };
    /**
     * Extra Shots
     */
    extra_shots?: number;
    /**
     * Penalties
     */
    penalties?: {
        [key: string]: number;
    };
};

/**
 * ActivityResultResponse
 *
 * Schema for activity result response
 */
export type ActivityResultResponse = {
    /**
     * Activity Id
     */
    activity_id: number;
    /**
     * Team Id
     */
    team_id: number;
    /**
     * Result Data
     */
    result_data?: {
        [key: string]: unknown;
    };
    /**
     * Extra Shots
     */
    extra_shots?: number;
    /**
     * Penalties
     */
    penalties?: {
        [key: string]: number;
    };
    /**
     * Id
     */
    id: number;
    /**
     * Time Score
     */
    time_score?: number | null;
    /**
     * Points Score
     */
    points_score?: number | null;
    /**
     * Boolean Score
     */
    boolean_score?: boolean | null;
    /**
     * Team Vs Result
     */
    team_vs_result?: string | null;
    /**
     * Final Score
     */
    final_score?: number | null;
    /**
     * Is Completed
     */
    is_completed?: boolean;
    /**
     * Completed At
     */
    completed_at?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ActivityResultUpdate
 *
 * Schema for updating an activity result
 */
export type ActivityResultUpdate = {
    /**
     * Result Data
     */
    result_data?: {
        [key: string]: unknown;
    } | null;
    /**
     * Extra Shots
     */
    extra_shots?: number | null;
    /**
     * Penalties
     */
    penalties?: {
        [key: string]: number;
    } | null;
    /**
     * Is Completed
     */
    is_completed?: boolean | null;
};

/**
 * ActivityType
 *
 * Enum for activity types with string values for database compatibility
 */
export type ActivityType = 'TimeBasedActivity' | 'ScoreBasedActivity' | 'BooleanActivity' | 'TeamVsActivity' | 'GeneralActivity';

/**
 * ActivityUpdate
 *
 * Schema for updating an activity
 */
export type ActivityUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * CheckPointCreate
 */
export type CheckPointCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Latitude
     */
    latitude?: number | null;
    /**
     * Longitude
     */
    longitude?: number | null;
    /**
     * Order
     */
    order: number;
};

/**
 * CheckPointUpdate
 */
export type CheckPointUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Latitude
     */
    latitude?: number | null;
    /**
     * Longitude
     */
    longitude?: number | null;
    /**
     * Order
     */
    order?: number | null;
};

/**
 * CheckpointAssignmentUpdate
 */
export type CheckpointAssignmentUpdate = {
    /**
     * Checkpoint Id
     */
    checkpoint_id?: number | null;
};

/**
 * DetailedCheckPoint
 */
export type DetailedCheckPoint = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description: string;
    /**
     * Latitude
     */
    latitude?: number | null;
    /**
     * Longitude
     */
    longitude?: number | null;
    /**
     * Order
     */
    order: number;
    /**
     * Id
     */
    id: number;
};

/**
 * DetailedTeam
 */
export type DetailedTeam = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Total
     */
    total: number;
    /**
     * Classification
     */
    classification: number;
    /**
     * Versus Group Id
     */
    versus_group_id?: number | null;
    /**
     * Times
     */
    times: Array<string>;
    /**
     * Score Per Checkpoint
     */
    score_per_checkpoint: Array<number>;
    /**
     * Members
     */
    members: Array<ListingUser>;
};

/**
 * DetailedUser
 */
export type DetailedUser = {
    /**
     * Name
     */
    name: string;
    /**
     * Team Id
     */
    team_id?: number | null;
    /**
     * Is Captain
     */
    is_captain?: boolean | null;
    /**
     * Id
     */
    id: number;
    /**
     * Disabled
     */
    disabled: boolean;
    /**
     * Staff Checkpoint Id
     */
    staff_checkpoint_id?: number | null;
};

/**
 * GlobalRanking
 *
 * Schema for global team ranking
 */
export type GlobalRanking = {
    /**
     * Rankings
     */
    rankings: Array<TeamRanking>;
    /**
     * Last Updated
     */
    last_updated: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ListingTeam
 *
 * The schema returned when listing multiple teams
 */
export type ListingTeam = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Total
     */
    total: number;
    /**
     * Classification
     */
    classification: number;
    /**
     * Versus Group Id
     */
    versus_group_id?: number | null;
    /**
     * Num Members
     */
    num_members: number;
    /**
     * Times
     */
    times?: Array<string>;
    /**
     * Last Checkpoint Time
     */
    last_checkpoint_time: string | null;
    /**
     * Last Checkpoint Score
     */
    last_checkpoint_score?: number | null;
    /**
     * Last Checkpoint Number
     */
    last_checkpoint_number?: number | null;
    /**
     * Last Checkpoint Name
     */
    last_checkpoint_name?: string | null;
};

/**
 * ListingUser
 */
export type ListingUser = {
    /**
     * Name
     */
    name: string;
    /**
     * Team Id
     */
    team_id?: number | null;
    /**
     * Is Captain
     */
    is_captain?: boolean | null;
    /**
     * Id
     */
    id: number;
};

/**
 * RallySettingsResponse
 */
export type RallySettingsResponse = {
    /**
     * Max Teams
     */
    max_teams: number;
    /**
     * Max Members Per Team
     */
    max_members_per_team: number;
    /**
     * Enable Versus
     */
    enable_versus: boolean;
    /**
     * Rally Start Time
     */
    rally_start_time?: string | null;
    /**
     * Rally End Time
     */
    rally_end_time?: string | null;
    /**
     * Penalty Per Puke
     */
    penalty_per_puke: number;
    /**
     * Penalty Per Not Drinking
     */
    penalty_per_not_drinking: number;
    /**
     * Bonus Per Extra Shot
     */
    bonus_per_extra_shot: number;
    /**
     * Max Extra Shots Per Member
     */
    max_extra_shots_per_member: number;
    /**
     * Checkpoint Order Matters
     */
    checkpoint_order_matters: boolean;
    /**
     * Enable Staff Scoring
     */
    enable_staff_scoring: boolean;
    /**
     * Show Live Leaderboard
     */
    show_live_leaderboard: boolean;
    /**
     * Show Team Details
     */
    show_team_details: boolean;
    /**
     * Show Checkpoint Map
     */
    show_checkpoint_map: boolean;
    /**
     * Rally Theme
     */
    rally_theme: string;
    /**
     * Public Access Enabled
     */
    public_access_enabled: boolean;
};

/**
 * RallySettingsUpdate
 */
export type RallySettingsUpdate = {
    /**
     * Max Teams
     */
    max_teams: number;
    /**
     * Max Members Per Team
     */
    max_members_per_team: number;
    /**
     * Enable Versus
     */
    enable_versus: boolean;
    /**
     * Rally Start Time
     */
    rally_start_time?: string | null;
    /**
     * Rally End Time
     */
    rally_end_time?: string | null;
    /**
     * Penalty Per Puke
     */
    penalty_per_puke: number;
    /**
     * Penalty Per Not Drinking
     */
    penalty_per_not_drinking: number;
    /**
     * Bonus Per Extra Shot
     */
    bonus_per_extra_shot: number;
    /**
     * Max Extra Shots Per Member
     */
    max_extra_shots_per_member: number;
    /**
     * Checkpoint Order Matters
     */
    checkpoint_order_matters: boolean;
    /**
     * Enable Staff Scoring
     */
    enable_staff_scoring: boolean;
    /**
     * Show Live Leaderboard
     */
    show_live_leaderboard: boolean;
    /**
     * Show Team Details
     */
    show_team_details: boolean;
    /**
     * Show Checkpoint Map
     */
    show_checkpoint_map: boolean;
    /**
     * Rally Theme
     */
    rally_theme: string;
    /**
     * Public Access Enabled
     */
    public_access_enabled: boolean;
};

/**
 * RallyStaffAssignmentWithCheckpoint
 *
 * Staff assignment with checkpoint details
 */
export type RallyStaffAssignmentWithCheckpoint = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Checkpoint Id
     */
    checkpoint_id?: number | null;
    /**
     * Id
     */
    id: number;
    /**
     * Checkpoint Name
     */
    checkpoint_name?: string | null;
    /**
     * Checkpoint Description
     */
    checkpoint_description?: string | null;
    /**
     * User Name
     */
    user_name?: string | null;
    /**
     * User Email
     */
    user_email?: string | null;
};

/**
 * TeamCreate
 */
export type TeamCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * TeamMemberAdd
 */
export type TeamMemberAdd = {
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Captain
     */
    is_captain?: boolean;
};

/**
 * TeamMemberResponse
 */
export type TeamMemberResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Captain
     */
    is_captain?: boolean;
};

/**
 * TeamMemberUpdate
 */
export type TeamMemberUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Captain
     */
    is_captain?: boolean | null;
};

/**
 * TeamRanking
 *
 * Schema for team ranking
 */
export type TeamRanking = {
    /**
     * Team Id
     */
    team_id: number;
    /**
     * Team Name
     */
    team_name: string;
    /**
     * Total Score
     */
    total_score: number;
    /**
     * Activities Completed
     */
    activities_completed: number;
    /**
     * Rank
     */
    rank: number;
};

/**
 * TeamScoresUpdate
 */
export type TeamScoresUpdate = {
    /**
     * Checkpoint Id
     */
    checkpoint_id?: number | null;
    /**
     * Question Score
     */
    question_score: number;
    /**
     * Time Score
     */
    time_score: number;
    /**
     * Pukes
     */
    pukes: number;
    /**
     * Skips
     */
    skips: number;
};

/**
 * TeamUpdate
 */
export type TeamUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Times
     */
    times?: Array<string> | null;
    /**
     * Score Per Checkpoint
     */
    score_per_checkpoint?: Array<number> | null;
    /**
     * Question Scores
     */
    question_scores?: Array<boolean> | null;
    /**
     * Time Scores
     */
    time_scores?: Array<number> | null;
    /**
     * Pukes
     */
    pukes?: number | null;
    /**
     * Skips
     */
    skips?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VersusGroupListResponse
 */
export type VersusGroupListResponse = {
    /**
     * Groups
     */
    groups: Array<VersusPairResponse>;
};

/**
 * VersusOpponentResponse
 */
export type VersusOpponentResponse = {
    /**
     * Opponent Id
     */
    opponent_id: number | null;
    /**
     * Opponent Name
     */
    opponent_name: string | null;
};

/**
 * VersusPairCreate
 */
export type VersusPairCreate = {
    /**
     * Team A Id
     */
    team_a_id: number;
    /**
     * Team B Id
     */
    team_b_id: number;
};

/**
 * VersusPairResponse
 */
export type VersusPairResponse = {
    /**
     * Group Id
     */
    group_id: number;
    /**
     * Team A Id
     */
    team_a_id: number;
    /**
     * Team B Id
     */
    team_b_id: number;
};

export type GetTeamsApiRallyV1TeamGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/team/';
};

export type GetTeamsApiRallyV1TeamGetResponses = {
    /**
     * Response Get Teams Api Rally V1 Team  Get
     *
     * Successful Response
     */
    200: Array<ListingTeam>;
};

export type GetTeamsApiRallyV1TeamGetResponse = GetTeamsApiRallyV1TeamGetResponses[keyof GetTeamsApiRallyV1TeamGetResponses];

export type CreateTeamApiRallyV1TeamPostData = {
    body: TeamCreate;
    path?: never;
    query?: never;
    url: '/api/rally/v1/team/';
};

export type CreateTeamApiRallyV1TeamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTeamApiRallyV1TeamPostError = CreateTeamApiRallyV1TeamPostErrors[keyof CreateTeamApiRallyV1TeamPostErrors];

export type CreateTeamApiRallyV1TeamPostResponses = {
    /**
     * Successful Response
     */
    201: DetailedTeam;
};

export type CreateTeamApiRallyV1TeamPostResponse = CreateTeamApiRallyV1TeamPostResponses[keyof CreateTeamApiRallyV1TeamPostResponses];

export type GetOwnTeamApiRallyV1TeamMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/team/me';
};

export type GetOwnTeamApiRallyV1TeamMeGetResponses = {
    /**
     * Successful Response
     */
    200: DetailedTeam;
};

export type GetOwnTeamApiRallyV1TeamMeGetResponse = GetOwnTeamApiRallyV1TeamMeGetResponses[keyof GetOwnTeamApiRallyV1TeamMeGetResponses];

export type DeleteTeamApiRallyV1TeamIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/rally/v1/team/{id}';
};

export type DeleteTeamApiRallyV1TeamIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTeamApiRallyV1TeamIdDeleteError = DeleteTeamApiRallyV1TeamIdDeleteErrors[keyof DeleteTeamApiRallyV1TeamIdDeleteErrors];

export type DeleteTeamApiRallyV1TeamIdDeleteResponses = {
    /**
     * Response Delete Team Api Rally V1 Team  Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteTeamApiRallyV1TeamIdDeleteResponse = DeleteTeamApiRallyV1TeamIdDeleteResponses[keyof DeleteTeamApiRallyV1TeamIdDeleteResponses];

export type GetTeamByIdApiRallyV1TeamIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/rally/v1/team/{id}';
};

export type GetTeamByIdApiRallyV1TeamIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeamByIdApiRallyV1TeamIdGetError = GetTeamByIdApiRallyV1TeamIdGetErrors[keyof GetTeamByIdApiRallyV1TeamIdGetErrors];

export type GetTeamByIdApiRallyV1TeamIdGetResponses = {
    /**
     * Successful Response
     */
    200: DetailedTeam;
};

export type GetTeamByIdApiRallyV1TeamIdGetResponse = GetTeamByIdApiRallyV1TeamIdGetResponses[keyof GetTeamByIdApiRallyV1TeamIdGetResponses];

export type UpdateTeamApiRallyV1TeamIdPutData = {
    body: TeamUpdate;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/rally/v1/team/{id}';
};

export type UpdateTeamApiRallyV1TeamIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTeamApiRallyV1TeamIdPutError = UpdateTeamApiRallyV1TeamIdPutErrors[keyof UpdateTeamApiRallyV1TeamIdPutErrors];

export type UpdateTeamApiRallyV1TeamIdPutResponses = {
    /**
     * Successful Response
     */
    200: DetailedTeam;
};

export type UpdateTeamApiRallyV1TeamIdPutResponse = UpdateTeamApiRallyV1TeamIdPutResponses[keyof UpdateTeamApiRallyV1TeamIdPutResponses];

export type AddCheckpointApiRallyV1TeamIdCheckpointPutData = {
    body: TeamScoresUpdate;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/rally/v1/team/{id}/checkpoint';
};

export type AddCheckpointApiRallyV1TeamIdCheckpointPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddCheckpointApiRallyV1TeamIdCheckpointPutError = AddCheckpointApiRallyV1TeamIdCheckpointPutErrors[keyof AddCheckpointApiRallyV1TeamIdCheckpointPutErrors];

export type AddCheckpointApiRallyV1TeamIdCheckpointPutResponses = {
    /**
     * Successful Response
     */
    201: DetailedTeam;
};

export type AddCheckpointApiRallyV1TeamIdCheckpointPutResponse = AddCheckpointApiRallyV1TeamIdCheckpointPutResponses[keyof AddCheckpointApiRallyV1TeamIdCheckpointPutResponses];

export type GetCheckpointsApiRallyV1CheckpointGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/checkpoint/';
};

export type GetCheckpointsApiRallyV1CheckpointGetResponses = {
    /**
     * Response Get Checkpoints Api Rally V1 Checkpoint  Get
     *
     * Successful Response
     */
    200: Array<DetailedCheckPoint>;
};

export type GetCheckpointsApiRallyV1CheckpointGetResponse = GetCheckpointsApiRallyV1CheckpointGetResponses[keyof GetCheckpointsApiRallyV1CheckpointGetResponses];

export type CreateCheckpointApiRallyV1CheckpointPostData = {
    body: CheckPointCreate;
    path?: never;
    query?: never;
    url: '/api/rally/v1/checkpoint/';
};

export type CreateCheckpointApiRallyV1CheckpointPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCheckpointApiRallyV1CheckpointPostError = CreateCheckpointApiRallyV1CheckpointPostErrors[keyof CreateCheckpointApiRallyV1CheckpointPostErrors];

export type CreateCheckpointApiRallyV1CheckpointPostResponses = {
    /**
     * Successful Response
     */
    201: DetailedCheckPoint;
};

export type CreateCheckpointApiRallyV1CheckpointPostResponse = CreateCheckpointApiRallyV1CheckpointPostResponses[keyof CreateCheckpointApiRallyV1CheckpointPostResponses];

export type GetNextCheckpointApiRallyV1CheckpointMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/checkpoint/me';
};

export type GetNextCheckpointApiRallyV1CheckpointMeGetResponses = {
    /**
     * Successful Response
     */
    200: DetailedCheckPoint;
};

export type GetNextCheckpointApiRallyV1CheckpointMeGetResponse = GetNextCheckpointApiRallyV1CheckpointMeGetResponses[keyof GetNextCheckpointApiRallyV1CheckpointMeGetResponses];

export type GetCheckpointTeamsApiRallyV1CheckpointTeamsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Checkpoint Id
         */
        checkpoint_id?: number | null;
    };
    url: '/api/rally/v1/checkpoint/teams';
};

export type GetCheckpointTeamsApiRallyV1CheckpointTeamsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCheckpointTeamsApiRallyV1CheckpointTeamsGetError = GetCheckpointTeamsApiRallyV1CheckpointTeamsGetErrors[keyof GetCheckpointTeamsApiRallyV1CheckpointTeamsGetErrors];

export type GetCheckpointTeamsApiRallyV1CheckpointTeamsGetResponses = {
    /**
     * Response Get Checkpoint Teams Api Rally V1 Checkpoint Teams Get
     *
     * Successful Response
     */
    200: Array<ListingTeam>;
};

export type GetCheckpointTeamsApiRallyV1CheckpointTeamsGetResponse = GetCheckpointTeamsApiRallyV1CheckpointTeamsGetResponses[keyof GetCheckpointTeamsApiRallyV1CheckpointTeamsGetResponses];

export type ReorderCheckpointsApiRallyV1CheckpointReorderPutData = {
    /**
     * Checkpoint Orders
     */
    body: {
        [key: string]: number;
    };
    path?: never;
    query?: never;
    url: '/api/rally/v1/checkpoint/reorder';
};

export type ReorderCheckpointsApiRallyV1CheckpointReorderPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReorderCheckpointsApiRallyV1CheckpointReorderPutError = ReorderCheckpointsApiRallyV1CheckpointReorderPutErrors[keyof ReorderCheckpointsApiRallyV1CheckpointReorderPutErrors];

export type ReorderCheckpointsApiRallyV1CheckpointReorderPutResponses = {
    /**
     * Response Reorder Checkpoints Api Rally V1 Checkpoint Reorder Put
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ReorderCheckpointsApiRallyV1CheckpointReorderPutResponse = ReorderCheckpointsApiRallyV1CheckpointReorderPutResponses[keyof ReorderCheckpointsApiRallyV1CheckpointReorderPutResponses];

export type DeleteCheckpointApiRallyV1CheckpointIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/rally/v1/checkpoint/{id}';
};

export type DeleteCheckpointApiRallyV1CheckpointIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCheckpointApiRallyV1CheckpointIdDeleteError = DeleteCheckpointApiRallyV1CheckpointIdDeleteErrors[keyof DeleteCheckpointApiRallyV1CheckpointIdDeleteErrors];

export type DeleteCheckpointApiRallyV1CheckpointIdDeleteResponses = {
    /**
     * Response Delete Checkpoint Api Rally V1 Checkpoint  Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteCheckpointApiRallyV1CheckpointIdDeleteResponse = DeleteCheckpointApiRallyV1CheckpointIdDeleteResponses[keyof DeleteCheckpointApiRallyV1CheckpointIdDeleteResponses];

export type UpdateCheckpointApiRallyV1CheckpointIdPutData = {
    body: CheckPointUpdate;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/rally/v1/checkpoint/{id}';
};

export type UpdateCheckpointApiRallyV1CheckpointIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCheckpointApiRallyV1CheckpointIdPutError = UpdateCheckpointApiRallyV1CheckpointIdPutErrors[keyof UpdateCheckpointApiRallyV1CheckpointIdPutErrors];

export type UpdateCheckpointApiRallyV1CheckpointIdPutResponses = {
    /**
     * Successful Response
     */
    200: DetailedCheckPoint;
};

export type UpdateCheckpointApiRallyV1CheckpointIdPutResponse = UpdateCheckpointApiRallyV1CheckpointIdPutResponses[keyof UpdateCheckpointApiRallyV1CheckpointIdPutResponses];

export type GetStaffAssignmentsApiRallyV1UserStaffAssignmentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/user/staff-assignments';
};

export type GetStaffAssignmentsApiRallyV1UserStaffAssignmentsGetResponses = {
    /**
     * Response Get Staff Assignments Api Rally V1 User Staff Assignments Get
     *
     * Successful Response
     */
    200: Array<RallyStaffAssignmentWithCheckpoint>;
};

export type GetStaffAssignmentsApiRallyV1UserStaffAssignmentsGetResponse = GetStaffAssignmentsApiRallyV1UserStaffAssignmentsGetResponses[keyof GetStaffAssignmentsApiRallyV1UserStaffAssignmentsGetResponses];

export type GetMeApiRallyV1UserMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/user/me';
};

export type GetMeApiRallyV1UserMeGetResponses = {
    /**
     * Response Get Me Api Rally V1 User Me Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetMeApiRallyV1UserMeGetResponse = GetMeApiRallyV1UserMeGetResponses[keyof GetMeApiRallyV1UserMeGetResponses];

export type UpdateCheckpointAssignmentApiRallyV1UserUserIdCheckpointAssignmentPutData = {
    body: CheckpointAssignmentUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/rally/v1/user/{user_id}/checkpoint-assignment';
};

export type UpdateCheckpointAssignmentApiRallyV1UserUserIdCheckpointAssignmentPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCheckpointAssignmentApiRallyV1UserUserIdCheckpointAssignmentPutError = UpdateCheckpointAssignmentApiRallyV1UserUserIdCheckpointAssignmentPutErrors[keyof UpdateCheckpointAssignmentApiRallyV1UserUserIdCheckpointAssignmentPutErrors];

export type UpdateCheckpointAssignmentApiRallyV1UserUserIdCheckpointAssignmentPutResponses = {
    /**
     * Successful Response
     */
    200: RallyStaffAssignmentWithCheckpoint;
};

export type UpdateCheckpointAssignmentApiRallyV1UserUserIdCheckpointAssignmentPutResponse = UpdateCheckpointAssignmentApiRallyV1UserUserIdCheckpointAssignmentPutResponses[keyof UpdateCheckpointAssignmentApiRallyV1UserUserIdCheckpointAssignmentPutResponses];

export type ViewRallySettingsApiRallyV1RallySettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/rally/settings';
};

export type ViewRallySettingsApiRallyV1RallySettingsGetResponses = {
    /**
     * Successful Response
     */
    200: RallySettingsResponse;
};

export type ViewRallySettingsApiRallyV1RallySettingsGetResponse = ViewRallySettingsApiRallyV1RallySettingsGetResponses[keyof ViewRallySettingsApiRallyV1RallySettingsGetResponses];

export type UpdateRallySettingsApiRallyV1RallySettingsPutData = {
    body: RallySettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/rally/v1/rally/settings';
};

export type UpdateRallySettingsApiRallyV1RallySettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRallySettingsApiRallyV1RallySettingsPutError = UpdateRallySettingsApiRallyV1RallySettingsPutErrors[keyof UpdateRallySettingsApiRallyV1RallySettingsPutErrors];

export type UpdateRallySettingsApiRallyV1RallySettingsPutResponses = {
    /**
     * Successful Response
     */
    200: RallySettingsResponse;
};

export type UpdateRallySettingsApiRallyV1RallySettingsPutResponse = UpdateRallySettingsApiRallyV1RallySettingsPutResponses[keyof UpdateRallySettingsApiRallyV1RallySettingsPutResponses];

export type ViewRallySettingsPublicApiRallyV1RallySettingsPublicGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/rally/settings/public';
};

export type ViewRallySettingsPublicApiRallyV1RallySettingsPublicGetResponses = {
    /**
     * Successful Response
     */
    200: RallySettingsResponse;
};

export type ViewRallySettingsPublicApiRallyV1RallySettingsPublicGetResponse = ViewRallySettingsPublicApiRallyV1RallySettingsPublicGetResponses[keyof ViewRallySettingsPublicApiRallyV1RallySettingsPublicGetResponses];

export type CreateVersusPairApiRallyV1VersusPairPostData = {
    body: VersusPairCreate;
    path?: never;
    query?: never;
    url: '/api/rally/v1/versus/pair';
};

export type CreateVersusPairApiRallyV1VersusPairPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateVersusPairApiRallyV1VersusPairPostError = CreateVersusPairApiRallyV1VersusPairPostErrors[keyof CreateVersusPairApiRallyV1VersusPairPostErrors];

export type CreateVersusPairApiRallyV1VersusPairPostResponses = {
    /**
     * Successful Response
     */
    200: VersusPairResponse;
};

export type CreateVersusPairApiRallyV1VersusPairPostResponse = CreateVersusPairApiRallyV1VersusPairPostResponses[keyof CreateVersusPairApiRallyV1VersusPairPostResponses];

export type GetTeamOpponentApiRallyV1VersusTeamTeamIdOpponentGetData = {
    body?: never;
    path: {
        /**
         * Team Id
         */
        team_id: number;
    };
    query?: never;
    url: '/api/rally/v1/versus/team/{team_id}/opponent';
};

export type GetTeamOpponentApiRallyV1VersusTeamTeamIdOpponentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeamOpponentApiRallyV1VersusTeamTeamIdOpponentGetError = GetTeamOpponentApiRallyV1VersusTeamTeamIdOpponentGetErrors[keyof GetTeamOpponentApiRallyV1VersusTeamTeamIdOpponentGetErrors];

export type GetTeamOpponentApiRallyV1VersusTeamTeamIdOpponentGetResponses = {
    /**
     * Successful Response
     */
    200: VersusOpponentResponse;
};

export type GetTeamOpponentApiRallyV1VersusTeamTeamIdOpponentGetResponse = GetTeamOpponentApiRallyV1VersusTeamTeamIdOpponentGetResponses[keyof GetTeamOpponentApiRallyV1VersusTeamTeamIdOpponentGetResponses];

export type ListVersusGroupsApiRallyV1VersusGroupsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/versus/groups';
};

export type ListVersusGroupsApiRallyV1VersusGroupsGetResponses = {
    /**
     * Successful Response
     */
    200: VersusGroupListResponse;
};

export type ListVersusGroupsApiRallyV1VersusGroupsGetResponse = ListVersusGroupsApiRallyV1VersusGroupsGetResponses[keyof ListVersusGroupsApiRallyV1VersusGroupsGetResponses];

export type GetTeamMembersApiRallyV1TeamTeamIdMembersGetData = {
    body?: never;
    path: {
        /**
         * Team Id
         */
        team_id: number;
    };
    query?: never;
    url: '/api/rally/v1/team/{team_id}/members';
};

export type GetTeamMembersApiRallyV1TeamTeamIdMembersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeamMembersApiRallyV1TeamTeamIdMembersGetError = GetTeamMembersApiRallyV1TeamTeamIdMembersGetErrors[keyof GetTeamMembersApiRallyV1TeamTeamIdMembersGetErrors];

export type GetTeamMembersApiRallyV1TeamTeamIdMembersGetResponses = {
    /**
     * Response Get Team Members Api Rally V1 Team  Team Id  Members Get
     *
     * Successful Response
     */
    200: Array<TeamMemberResponse>;
};

export type GetTeamMembersApiRallyV1TeamTeamIdMembersGetResponse = GetTeamMembersApiRallyV1TeamTeamIdMembersGetResponses[keyof GetTeamMembersApiRallyV1TeamTeamIdMembersGetResponses];

export type AddTeamMemberApiRallyV1TeamTeamIdMembersPostData = {
    body: TeamMemberAdd;
    path: {
        /**
         * Team Id
         */
        team_id: number;
    };
    query?: never;
    url: '/api/rally/v1/team/{team_id}/members';
};

export type AddTeamMemberApiRallyV1TeamTeamIdMembersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddTeamMemberApiRallyV1TeamTeamIdMembersPostError = AddTeamMemberApiRallyV1TeamTeamIdMembersPostErrors[keyof AddTeamMemberApiRallyV1TeamTeamIdMembersPostErrors];

export type AddTeamMemberApiRallyV1TeamTeamIdMembersPostResponses = {
    /**
     * Successful Response
     */
    201: TeamMemberResponse;
};

export type AddTeamMemberApiRallyV1TeamTeamIdMembersPostResponse = AddTeamMemberApiRallyV1TeamTeamIdMembersPostResponses[keyof AddTeamMemberApiRallyV1TeamTeamIdMembersPostResponses];

export type RemoveTeamMemberApiRallyV1TeamTeamIdMembersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * Team Id
         */
        team_id: number;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/rally/v1/team/{team_id}/members/{user_id}';
};

export type RemoveTeamMemberApiRallyV1TeamTeamIdMembersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoveTeamMemberApiRallyV1TeamTeamIdMembersUserIdDeleteError = RemoveTeamMemberApiRallyV1TeamTeamIdMembersUserIdDeleteErrors[keyof RemoveTeamMemberApiRallyV1TeamTeamIdMembersUserIdDeleteErrors];

export type RemoveTeamMemberApiRallyV1TeamTeamIdMembersUserIdDeleteResponses = {
    /**
     * Response Remove Team Member Api Rally V1 Team  Team Id  Members  User Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RemoveTeamMemberApiRallyV1TeamTeamIdMembersUserIdDeleteResponse = RemoveTeamMemberApiRallyV1TeamTeamIdMembersUserIdDeleteResponses[keyof RemoveTeamMemberApiRallyV1TeamTeamIdMembersUserIdDeleteResponses];

export type UpdateTeamMemberApiRallyV1TeamTeamIdMembersUserIdPutData = {
    body: TeamMemberUpdate;
    path: {
        /**
         * Team Id
         */
        team_id: number;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/rally/v1/team/{team_id}/members/{user_id}';
};

export type UpdateTeamMemberApiRallyV1TeamTeamIdMembersUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTeamMemberApiRallyV1TeamTeamIdMembersUserIdPutError = UpdateTeamMemberApiRallyV1TeamTeamIdMembersUserIdPutErrors[keyof UpdateTeamMemberApiRallyV1TeamTeamIdMembersUserIdPutErrors];

export type UpdateTeamMemberApiRallyV1TeamTeamIdMembersUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: TeamMemberResponse;
};

export type UpdateTeamMemberApiRallyV1TeamTeamIdMembersUserIdPutResponse = UpdateTeamMemberApiRallyV1TeamTeamIdMembersUserIdPutResponses[keyof UpdateTeamMemberApiRallyV1TeamTeamIdMembersUserIdPutResponses];

export type GetActivitiesApiRallyV1ActivitiesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Checkpoint Id
         */
        checkpoint_id?: number | null;
    };
    url: '/api/rally/v1/activities/';
};

export type GetActivitiesApiRallyV1ActivitiesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActivitiesApiRallyV1ActivitiesGetError = GetActivitiesApiRallyV1ActivitiesGetErrors[keyof GetActivitiesApiRallyV1ActivitiesGetErrors];

export type GetActivitiesApiRallyV1ActivitiesGetResponses = {
    /**
     * Successful Response
     */
    200: ActivityListResponse;
};

export type GetActivitiesApiRallyV1ActivitiesGetResponse = GetActivitiesApiRallyV1ActivitiesGetResponses[keyof GetActivitiesApiRallyV1ActivitiesGetResponses];

export type CreateActivityApiRallyV1ActivitiesPostData = {
    body: ActivityCreate;
    path?: never;
    query?: never;
    url: '/api/rally/v1/activities/';
};

export type CreateActivityApiRallyV1ActivitiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateActivityApiRallyV1ActivitiesPostError = CreateActivityApiRallyV1ActivitiesPostErrors[keyof CreateActivityApiRallyV1ActivitiesPostErrors];

export type CreateActivityApiRallyV1ActivitiesPostResponses = {
    /**
     * Successful Response
     */
    200: ActivityResponse;
};

export type CreateActivityApiRallyV1ActivitiesPostResponse = CreateActivityApiRallyV1ActivitiesPostResponses[keyof CreateActivityApiRallyV1ActivitiesPostResponses];

export type GetAllActivityResultsApiRallyV1ActivitiesResultsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/activities/results';
};

export type GetAllActivityResultsApiRallyV1ActivitiesResultsGetResponses = {
    /**
     * Response Get All Activity Results Api Rally V1 Activities Results Get
     *
     * Successful Response
     */
    200: Array<ActivityResultResponse>;
};

export type GetAllActivityResultsApiRallyV1ActivitiesResultsGetResponse = GetAllActivityResultsApiRallyV1ActivitiesResultsGetResponses[keyof GetAllActivityResultsApiRallyV1ActivitiesResultsGetResponses];

export type DeleteActivityApiRallyV1ActivitiesActivityIdDeleteData = {
    body?: never;
    path: {
        /**
         * Activity Id
         */
        activity_id: number;
    };
    query?: never;
    url: '/api/rally/v1/activities/{activity_id}';
};

export type DeleteActivityApiRallyV1ActivitiesActivityIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteActivityApiRallyV1ActivitiesActivityIdDeleteError = DeleteActivityApiRallyV1ActivitiesActivityIdDeleteErrors[keyof DeleteActivityApiRallyV1ActivitiesActivityIdDeleteErrors];

export type DeleteActivityApiRallyV1ActivitiesActivityIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetActivityApiRallyV1ActivitiesActivityIdGetData = {
    body?: never;
    path: {
        /**
         * Activity Id
         */
        activity_id: number;
    };
    query?: never;
    url: '/api/rally/v1/activities/{activity_id}';
};

export type GetActivityApiRallyV1ActivitiesActivityIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActivityApiRallyV1ActivitiesActivityIdGetError = GetActivityApiRallyV1ActivitiesActivityIdGetErrors[keyof GetActivityApiRallyV1ActivitiesActivityIdGetErrors];

export type GetActivityApiRallyV1ActivitiesActivityIdGetResponses = {
    /**
     * Successful Response
     */
    200: ActivityResponse;
};

export type GetActivityApiRallyV1ActivitiesActivityIdGetResponse = GetActivityApiRallyV1ActivitiesActivityIdGetResponses[keyof GetActivityApiRallyV1ActivitiesActivityIdGetResponses];

export type UpdateActivityApiRallyV1ActivitiesActivityIdPutData = {
    body: ActivityUpdate;
    path: {
        /**
         * Activity Id
         */
        activity_id: number;
    };
    query?: never;
    url: '/api/rally/v1/activities/{activity_id}';
};

export type UpdateActivityApiRallyV1ActivitiesActivityIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateActivityApiRallyV1ActivitiesActivityIdPutError = UpdateActivityApiRallyV1ActivitiesActivityIdPutErrors[keyof UpdateActivityApiRallyV1ActivitiesActivityIdPutErrors];

export type UpdateActivityApiRallyV1ActivitiesActivityIdPutResponses = {
    /**
     * Successful Response
     */
    200: ActivityResponse;
};

export type UpdateActivityApiRallyV1ActivitiesActivityIdPutResponse = UpdateActivityApiRallyV1ActivitiesActivityIdPutResponses[keyof UpdateActivityApiRallyV1ActivitiesActivityIdPutResponses];

export type CreateActivityResultApiRallyV1ActivitiesResultsPostData = {
    body: ActivityResultCreate;
    path?: never;
    query?: never;
    url: '/api/rally/v1/activities/results/';
};

export type CreateActivityResultApiRallyV1ActivitiesResultsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateActivityResultApiRallyV1ActivitiesResultsPostError = CreateActivityResultApiRallyV1ActivitiesResultsPostErrors[keyof CreateActivityResultApiRallyV1ActivitiesResultsPostErrors];

export type CreateActivityResultApiRallyV1ActivitiesResultsPostResponses = {
    /**
     * Successful Response
     */
    200: ActivityResultResponse;
};

export type CreateActivityResultApiRallyV1ActivitiesResultsPostResponse = CreateActivityResultApiRallyV1ActivitiesResultsPostResponses[keyof CreateActivityResultApiRallyV1ActivitiesResultsPostResponses];

export type GetActivityResultApiRallyV1ActivitiesResultsResultIdGetData = {
    body?: never;
    path: {
        /**
         * Result Id
         */
        result_id: number;
    };
    query?: never;
    url: '/api/rally/v1/activities/results/{result_id}';
};

export type GetActivityResultApiRallyV1ActivitiesResultsResultIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActivityResultApiRallyV1ActivitiesResultsResultIdGetError = GetActivityResultApiRallyV1ActivitiesResultsResultIdGetErrors[keyof GetActivityResultApiRallyV1ActivitiesResultsResultIdGetErrors];

export type GetActivityResultApiRallyV1ActivitiesResultsResultIdGetResponses = {
    /**
     * Successful Response
     */
    200: ActivityResultResponse;
};

export type GetActivityResultApiRallyV1ActivitiesResultsResultIdGetResponse = GetActivityResultApiRallyV1ActivitiesResultsResultIdGetResponses[keyof GetActivityResultApiRallyV1ActivitiesResultsResultIdGetResponses];

export type UpdateActivityResultApiRallyV1ActivitiesResultsResultIdPutData = {
    body: ActivityResultUpdate;
    path: {
        /**
         * Result Id
         */
        result_id: number;
    };
    query?: never;
    url: '/api/rally/v1/activities/results/{result_id}';
};

export type UpdateActivityResultApiRallyV1ActivitiesResultsResultIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateActivityResultApiRallyV1ActivitiesResultsResultIdPutError = UpdateActivityResultApiRallyV1ActivitiesResultsResultIdPutErrors[keyof UpdateActivityResultApiRallyV1ActivitiesResultsResultIdPutErrors];

export type UpdateActivityResultApiRallyV1ActivitiesResultsResultIdPutResponses = {
    /**
     * Successful Response
     */
    200: ActivityResultResponse;
};

export type UpdateActivityResultApiRallyV1ActivitiesResultsResultIdPutResponse = UpdateActivityResultApiRallyV1ActivitiesResultsResultIdPutResponses[keyof UpdateActivityResultApiRallyV1ActivitiesResultsResultIdPutResponses];

export type ApplyExtraShotsApiRallyV1ActivitiesResultsResultIdExtraShotsPostData = {
    body?: never;
    path: {
        /**
         * Result Id
         */
        result_id: number;
    };
    query: {
        /**
         * Extra Shots
         */
        extra_shots: number;
    };
    url: '/api/rally/v1/activities/results/{result_id}/extra-shots';
};

export type ApplyExtraShotsApiRallyV1ActivitiesResultsResultIdExtraShotsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApplyExtraShotsApiRallyV1ActivitiesResultsResultIdExtraShotsPostError = ApplyExtraShotsApiRallyV1ActivitiesResultsResultIdExtraShotsPostErrors[keyof ApplyExtraShotsApiRallyV1ActivitiesResultsResultIdExtraShotsPostErrors];

export type ApplyExtraShotsApiRallyV1ActivitiesResultsResultIdExtraShotsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ApplyPenaltyApiRallyV1ActivitiesResultsResultIdPenaltyPostData = {
    body?: never;
    path: {
        /**
         * Result Id
         */
        result_id: number;
    };
    query: {
        /**
         * Penalty Type
         */
        penalty_type: string;
        /**
         * Penalty Value
         */
        penalty_value: number;
    };
    url: '/api/rally/v1/activities/results/{result_id}/penalty';
};

export type ApplyPenaltyApiRallyV1ActivitiesResultsResultIdPenaltyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApplyPenaltyApiRallyV1ActivitiesResultsResultIdPenaltyPostError = ApplyPenaltyApiRallyV1ActivitiesResultsResultIdPenaltyPostErrors[keyof ApplyPenaltyApiRallyV1ActivitiesResultsResultIdPenaltyPostErrors];

export type ApplyPenaltyApiRallyV1ActivitiesResultsResultIdPenaltyPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetActivityRankingApiRallyV1ActivitiesActivityIdRankingGetData = {
    body?: never;
    path: {
        /**
         * Activity Id
         */
        activity_id: number;
    };
    query?: never;
    url: '/api/rally/v1/activities/{activity_id}/ranking';
};

export type GetActivityRankingApiRallyV1ActivitiesActivityIdRankingGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActivityRankingApiRallyV1ActivitiesActivityIdRankingGetError = GetActivityRankingApiRallyV1ActivitiesActivityIdRankingGetErrors[keyof GetActivityRankingApiRallyV1ActivitiesActivityIdRankingGetErrors];

export type GetActivityRankingApiRallyV1ActivitiesActivityIdRankingGetResponses = {
    /**
     * Successful Response
     */
    200: ActivityRanking;
};

export type GetActivityRankingApiRallyV1ActivitiesActivityIdRankingGetResponse = GetActivityRankingApiRallyV1ActivitiesActivityIdRankingGetResponses[keyof GetActivityRankingApiRallyV1ActivitiesActivityIdRankingGetResponses];

export type GetGlobalRankingApiRallyV1ActivitiesRankingGlobalGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/activities/ranking/global';
};

export type GetGlobalRankingApiRallyV1ActivitiesRankingGlobalGetResponses = {
    /**
     * Successful Response
     */
    200: GlobalRanking;
};

export type GetGlobalRankingApiRallyV1ActivitiesRankingGlobalGetResponse = GetGlobalRankingApiRallyV1ActivitiesRankingGlobalGetResponses[keyof GetGlobalRankingApiRallyV1ActivitiesRankingGlobalGetResponses];

export type CreateTeamVsResultApiRallyV1ActivitiesTeamVsActivityIdPostData = {
    /**
     * Match Data
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Activity Id
         */
        activity_id: number;
    };
    query: {
        /**
         * Team1 Id
         */
        team1_id: number;
        /**
         * Team2 Id
         */
        team2_id: number;
        /**
         * Winner Id
         */
        winner_id: number;
    };
    url: '/api/rally/v1/activities/team-vs/{activity_id}';
};

export type CreateTeamVsResultApiRallyV1ActivitiesTeamVsActivityIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTeamVsResultApiRallyV1ActivitiesTeamVsActivityIdPostError = CreateTeamVsResultApiRallyV1ActivitiesTeamVsActivityIdPostErrors[keyof CreateTeamVsResultApiRallyV1ActivitiesTeamVsActivityIdPostErrors];

export type CreateTeamVsResultApiRallyV1ActivitiesTeamVsActivityIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetActivityStatisticsApiRallyV1ActivitiesActivityIdStatisticsGetData = {
    body?: never;
    path: {
        /**
         * Activity Id
         */
        activity_id: number;
    };
    query?: never;
    url: '/api/rally/v1/activities/{activity_id}/statistics';
};

export type GetActivityStatisticsApiRallyV1ActivitiesActivityIdStatisticsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActivityStatisticsApiRallyV1ActivitiesActivityIdStatisticsGetError = GetActivityStatisticsApiRallyV1ActivitiesActivityIdStatisticsGetErrors[keyof GetActivityStatisticsApiRallyV1ActivitiesActivityIdStatisticsGetErrors];

export type GetActivityStatisticsApiRallyV1ActivitiesActivityIdStatisticsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMyCheckpointApiRallyV1StaffMyCheckpointGetData = {
    /**
     * Curr User
     */
    body?: DetailedUser;
    path?: never;
    query?: never;
    url: '/api/rally/v1/staff/my-checkpoint';
};

export type GetMyCheckpointApiRallyV1StaffMyCheckpointGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyCheckpointApiRallyV1StaffMyCheckpointGetError = GetMyCheckpointApiRallyV1StaffMyCheckpointGetErrors[keyof GetMyCheckpointApiRallyV1StaffMyCheckpointGetErrors];

export type GetMyCheckpointApiRallyV1StaffMyCheckpointGetResponses = {
    /**
     * Successful Response
     */
    200: DetailedCheckPoint;
};

export type GetMyCheckpointApiRallyV1StaffMyCheckpointGetResponse = GetMyCheckpointApiRallyV1StaffMyCheckpointGetResponses[keyof GetMyCheckpointApiRallyV1StaffMyCheckpointGetResponses];

export type GetTeamsAtMyCheckpointApiRallyV1StaffTeamsGetData = {
    /**
     * Curr User
     */
    body?: DetailedUser;
    path?: never;
    query?: never;
    url: '/api/rally/v1/staff/teams';
};

export type GetTeamsAtMyCheckpointApiRallyV1StaffTeamsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeamsAtMyCheckpointApiRallyV1StaffTeamsGetError = GetTeamsAtMyCheckpointApiRallyV1StaffTeamsGetErrors[keyof GetTeamsAtMyCheckpointApiRallyV1StaffTeamsGetErrors];

export type GetTeamsAtMyCheckpointApiRallyV1StaffTeamsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetTeamActivitiesForEvaluationApiRallyV1StaffTeamsTeamIdActivitiesGetData = {
    /**
     * Curr User
     */
    body?: DetailedUser;
    path: {
        /**
         * Team Id
         */
        team_id: number;
    };
    query?: never;
    url: '/api/rally/v1/staff/teams/{team_id}/activities';
};

export type GetTeamActivitiesForEvaluationApiRallyV1StaffTeamsTeamIdActivitiesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeamActivitiesForEvaluationApiRallyV1StaffTeamsTeamIdActivitiesGetError = GetTeamActivitiesForEvaluationApiRallyV1StaffTeamsTeamIdActivitiesGetErrors[keyof GetTeamActivitiesForEvaluationApiRallyV1StaffTeamsTeamIdActivitiesGetErrors];

export type GetTeamActivitiesForEvaluationApiRallyV1StaffTeamsTeamIdActivitiesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EvaluateTeamActivityApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluatePostData = {
    body: ActivityResultEvaluation;
    path: {
        /**
         * Team Id
         */
        team_id: number;
        /**
         * Activity Id
         */
        activity_id: number;
    };
    query?: never;
    url: '/api/rally/v1/staff/teams/{team_id}/activities/{activity_id}/evaluate';
};

export type EvaluateTeamActivityApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EvaluateTeamActivityApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluatePostError = EvaluateTeamActivityApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluatePostErrors[keyof EvaluateTeamActivityApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluatePostErrors];

export type EvaluateTeamActivityApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluatePostResponses = {
    /**
     * Successful Response
     */
    200: ActivityResultResponse;
};

export type EvaluateTeamActivityApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluatePostResponse = EvaluateTeamActivityApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluatePostResponses[keyof EvaluateTeamActivityApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluatePostResponses];

export type UpdateTeamActivityEvaluationApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluateResultIdPutData = {
    body: ActivityResultUpdate;
    path: {
        /**
         * Team Id
         */
        team_id: number;
        /**
         * Activity Id
         */
        activity_id: number;
        /**
         * Result Id
         */
        result_id: number;
    };
    query?: never;
    url: '/api/rally/v1/staff/teams/{team_id}/activities/{activity_id}/evaluate/{result_id}';
};

export type UpdateTeamActivityEvaluationApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluateResultIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTeamActivityEvaluationApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluateResultIdPutError = UpdateTeamActivityEvaluationApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluateResultIdPutErrors[keyof UpdateTeamActivityEvaluationApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluateResultIdPutErrors];

export type UpdateTeamActivityEvaluationApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluateResultIdPutResponses = {
    /**
     * Successful Response
     */
    200: ActivityResultResponse;
};

export type UpdateTeamActivityEvaluationApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluateResultIdPutResponse = UpdateTeamActivityEvaluationApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluateResultIdPutResponses[keyof UpdateTeamActivityEvaluationApiRallyV1StaffTeamsTeamIdActivitiesActivityIdEvaluateResultIdPutResponses];

export type GetAllEvaluationsApiRallyV1StaffAllEvaluationsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Checkpoint Id
         */
        checkpoint_id?: number | null;
    };
    url: '/api/rally/v1/staff/all-evaluations';
};

export type GetAllEvaluationsApiRallyV1StaffAllEvaluationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAllEvaluationsApiRallyV1StaffAllEvaluationsGetError = GetAllEvaluationsApiRallyV1StaffAllEvaluationsGetErrors[keyof GetAllEvaluationsApiRallyV1StaffAllEvaluationsGetErrors];

export type GetAllEvaluationsApiRallyV1StaffAllEvaluationsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRallyDurationApiRallyV1RallyDurationGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rally/v1/rally/duration';
};

export type GetRallyDurationApiRallyV1RallyDurationGetResponses = {
    /**
     * Response Get Rally Duration Api Rally V1 Rally Duration Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetRallyDurationApiRallyV1RallyDurationGetResponse = GetRallyDurationApiRallyV1RallyDurationGetResponses[keyof GetRallyDurationApiRallyV1RallyDurationGetResponses];

export type GetTeamRallyDurationApiRallyV1RallyTeamDurationTeamIdGetData = {
    body?: never;
    path: {
        /**
         * Team Id
         */
        team_id: number;
    };
    query?: never;
    url: '/api/rally/v1/rally/team-duration/{team_id}';
};

export type GetTeamRallyDurationApiRallyV1RallyTeamDurationTeamIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeamRallyDurationApiRallyV1RallyTeamDurationTeamIdGetError = GetTeamRallyDurationApiRallyV1RallyTeamDurationTeamIdGetErrors[keyof GetTeamRallyDurationApiRallyV1RallyTeamDurationTeamIdGetErrors];

export type GetTeamRallyDurationApiRallyV1RallyTeamDurationTeamIdGetResponses = {
    /**
     * Response Get Team Rally Duration Api Rally V1 Rally Team Duration  Team Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetTeamRallyDurationApiRallyV1RallyTeamDurationTeamIdGetResponse = GetTeamRallyDurationApiRallyV1RallyTeamDurationTeamIdGetResponses[keyof GetTeamRallyDurationApiRallyV1RallyTeamDurationTeamIdGetResponses];
