import fs from "node:fs";
import { test, expect, type Browser, type BrowserContext, type Page } from "@playwright/test";
import { seedRealOidcSession, apiCall, API_V1 } from "./helpers/fullstackAuth";
import { waitForApi } from "./helpers/seedRally";
import { seedPeddyTascasCast } from "./helpers/seedPeddyTascasCast";
import {
  AVEIRO_POSTS,
  AVEIRO_STAGES,
  FORA_DA_UNI_POSTS,
  UNIVERSIDADE_POSTS,
  type AveiroPost,
} from "./helpers/aveiroEvent";

/**
 * A real past edition: the NEI peddy paper through Aveiro, rebuilt from the
 * organizers' own planning sheet and then run.
 *
 * `master-peddy-tascas-day.spec.ts` covers a day whose route was invented to
 * exercise the mode. This one is the opposite: the route is fixed by what
 * actually happened, and the test has to cope with whatever that route needs.
 * That turns out to be a much harder brief, because a real plan uses the
 * corners of the product a synthetic one never reaches:
 *
 *  - Every post carries three separate texts — what the person stationed
 *    there talks about, the clue that gets a team there, and the challenge
 *    once they arrive (`staff_script` / `clue` / `challenge_brief`). Nothing
 *    in this suite had ever filled the first and third.
 *  - The route is in two blocks with different rules: the university posts in
 *    order, the ones outside as a set where three of four are enough. That is
 *    `RouteStage`, previously listed in this directory's README as untested.
 *  - One venue was still undecided ("CF DECIDE") — a provisional name teams
 *    must not see, which is `is_draft` + `is_placeholder`, and which the
 *    backend refuses to change once teams have started.
 *  - The challenges are not all the same shape. A ball at a goal is pass/fail
 *    but counts misses; questions in pairs are scored; a pyramid and a line of
 *    shots is against the clock; "mais criativo recebe uma salva de palmas"
 *    cannot be judged at the post at all — it needs every team's attempt
 *    first. Those are four different activity types and two penalty counters.
 *
 * And it is run the way a real one runs: the guides, the teams and the staff
 * evaluations all happening at the same time, not in turns.
 */

test.describe.configure({ mode: "serial" });

const TEAM_NAMES = ["Moliceiros", "Ovos Moles", "Salineiros", "Tunos"] as const;

/**
 * Which config key each of the admin form's type-specific inputs writes to
 * (ActivityConfigFields). Spelled out rather than derived, so that a form that
 * quietly points its "Pontos Máximos" box at the wrong key fails here.
 */
const CONFIG_KEY_BY_FIELD_ID: Readonly<Record<string, string>> = {
  "config-bool-success": "success_points",
  "config-bool-failure": "failure_points",
  "config-sb-max-points": "max_points",
  "config-sb-base-score": "base_score",
  "config-tb-max-points": "max_points",
  "config-tb-min-points": "min_points",
  "config-gen-min-points": "min_points",
  "config-gen-max-points": "max_points",
  "config-gen-default-points": "default_points",
  "config-dj-min-points": "min_points",
  "config-dj-max-points": "max_points",
};
const ARRIVAL_RADIUS_M = 80;

interface BuiltPost extends AveiroPost {
  readonly id: number;
  readonly fullName: string;
  readonly order: number;
  readonly activityId: number;
}

interface BuiltTeam {
  readonly id: number;
  readonly name: string;
  readonly accessCode: string;
}

interface AveiroWorld {
  readonly cast: Awaited<ReturnType<typeof seedPeddyTascasCast>>;
  readonly eventId: number;
  readonly eventName: string;
  readonly posts: readonly BuiltPost[];
  readonly teams: readonly BuiltTeam[];
}

let world: AveiroWorld;

function postByKey(key: string): BuiltPost {
  const post = world.posts.find((p) => p.key === key);
  if (!post) throw new Error(`post ${key} was never built`);
  return post;
}

async function newPage(browser: Browser): Promise<Page> {
  return (await browser.newContext()).newPage();
}

async function newAuthedPage(
  browser: Browser,
  user: Parameters<typeof seedRealOidcSession>[1],
): Promise<Page> {
  const context = await browser.newContext();
  await seedRealOidcSession(context, user);
  return context.newPage();
}

async function standAt(context: BrowserContext, post: BuiltPost) {
  await context.grantPermissions(["geolocation"]);
  await context.setGeolocation({ latitude: post.latitude, longitude: post.longitude });
}


/**
 * Flip a switch inside the admin checkpoint form.
 *
 * The visible control is a styled <label> wrapping a visually-hidden checkbox
 * (components/ui/switch.tsx), and the checkbox's id is generated by shadcn's
 * form context rather than taken from the field name — so the row's
 * `data-admin-search-key` is what identifies it.
 */
async function toggleFormSwitch(page: Page, searchKey: string): Promise<void> {
  const row = page.locator(`[data-admin-search-key="${searchKey}"]`);
  const checkbox = row.locator('input[type="checkbox"]');
  const before = await checkbox.isChecked();
  // The label that *wraps* the input, not the row's caption label — clicking
  // the wrapper is what a person does, and it works whether or not the
  // generated id and htmlFor happen to line up.
  await row.locator('label:has(input[type="checkbox"])').click();
  await expect(checkbox).toBeChecked({ checked: !before });
}

/**
 * Open one team's evaluation at the staff's post and return the open form.
 *
 * The staff screen lists the teams waiting at the post; picking one and
 * pressing "Avaliar" is what a staff member does between challenges.
 */
async function openEvaluation(page: Page, teamName: string): Promise<void> {
  await page.getByText(teamName).first().click();
  // Retried as a unit: the warning dialog renders a tick after the team is
  // opened, so a one-shot "is it there?" check races it and the click that
  // follows is then intercepted by an overlay that appeared in between.
  await expect(async () => {
    await dismissIncompleteWarning(page);
    await page
      .getByRole("button", { name: /avaliar|evaluate/i })
      .first()
      .click({ timeout: 3_000 });
  }).toPass({ timeout: 30_000 });
}

/**
 * Clear the "Avaliações incompletas detetadas" dialog if it is up.
 *
 * It fires when the team being opened belongs to a different post than the one
 * the staff member is standing at — which, in a free-choice block, is the
 * normal case rather than an error: the teams fan out, so whoever is at the
 * Faina is routinely handed a team whose "current" post is the Museu. The
 * dialog is a full-screen overlay, so until it is closed every click on the
 * page underneath is intercepted.
 */
async function dismissIncompleteWarning(page: Page): Promise<void> {
  const warning = page.getByText("Avaliações incompletas detetadas");
  if (await warning.isVisible().catch(() => false)) {
    await page.getByRole("button", { name: "Fechar" }).click();
    await expect(warning).toBeHidden({ timeout: 15_000 });
  }
}

const SUBMIT_EVALUATION = /submit evaluation|submeter avaliação|atualizar avaliação/i;

/**
 * Finish an evaluation and wait for the toast that means the POST landed.
 *
 * Matched exactly: a looser "avaliad[ao]" also matches the "Já avaliadas"
 * heading that appears as soon as any team at this post has been scored, so it
 * would pass whether or not this submission worked. `.first()` because
 * consecutive submissions stack toasts faster than each one's dismiss timer.
 */
async function submitEvaluation(page: Page): Promise<void> {
  await page.getByRole("button", { name: SUBMIT_EVALUATION }).click();
  await expect(page.getByText("Atividade avaliada com sucesso!").first()).toBeVisible({
    timeout: 20_000,
  });
  await dismissIncompleteWarning(page);
  await page.getByText("Voltar às equipas").click();
}

/**
 * Type a count into one of the activity's custom miss counters.
 *
 * These are the "cada falha bebe" counters configured per activity; the input
 * is labelled "Contagem de {label}" (PenaltiesFieldset), which is the only
 * stable handle on a control whose id is derived from a slug of the label.
 */
async function setPenaltyCount(page: Page, counterLabel: string, count: number): Promise<void> {
  await page.getByLabel(`Contagem de ${counterLabel}`).fill(String(count));
}

async function evaluateBoolean(
  page: Page,
  teamName: string,
  options: { success: boolean; counterLabel: string; count: number },
): Promise<void> {
  await openEvaluation(page, teamName);
  if (options.success) {
    // BooleanForm's success control is a visually-hidden checkbox under a
    // styled label — the label is the clickable thing.
    await page.getByText("Equipa teve sucesso na atividade").first().click();
  }
  await setPenaltyCount(page, options.counterLabel, options.count);
  await submitEvaluation(page);
}

async function evaluateScoreBased(
  page: Page,
  teamName: string,
  options: { score: number; counterLabel: string; count: number },
): Promise<void> {
  await openEvaluation(page, teamName);
  await page.locator("#score-achieved").fill(String(options.score));
  await setPenaltyCount(page, options.counterLabel, options.count);
  await submitEvaluation(page);
}

async function evaluateTimeBased(page: Page, teamName: string, seconds: number): Promise<void> {
  await openEvaluation(page, teamName);
  await page.locator("#timebased-completion-time").fill(String(seconds));
  await submitEvaluation(page);
}

async function evaluateGeneral(page: Page, teamName: string, points: number): Promise<void> {
  await openEvaluation(page, teamName);
  await page.locator("#general-points").fill(String(points));
  await submitEvaluation(page);
}

/**
 * Log a team in the way a team actually does: typing its access code into the
 * form on the phone.
 *
 * Kept for the teams that are proving the login screen works. The rest get a
 * seeded session instead, because `check_login_rate_limit` is keyed per client
 * IP rather than per access code (see this directory's README) and the whole
 * suite shares one runner IP.
 */
async function teamLoginThroughForm(page: Page, accessCode: string): Promise<void> {
  await page.goto("/rally/team-login");
  await page.getByPlaceholder("XXXX-XXXX").fill(accessCode);
  await page.getByRole("button", { name: "Entrar", exact: true }).click();
  await page.waitForURL("**/team-progress");
}

/**
 * Reach a post the way a team does: standing there and pressing the button.
 *
 * Retried as a whole because the geolocation-gated check-in can come back as a
 * transient error while the rest of the suite is hammering the same backend,
 * and because the button relabels itself between states ("Check-in GPS" →
 * "Tentar novamente") — so the retry has to re-find it rather than hold a
 * stale handle.
 */
async function checkInWithGpsButton(page: Page): Promise<void> {
  const registered = page.getByText(/Posto concluído|Check-in registado|Já registado/);
  const button = page.getByRole("button", { name: /^(Check-in GPS|Tentar novamente)$/ });
  let attempt = 0;
  await expect(async () => {
    // Checked first, so the retry is idempotent: a successful press relabels
    // the button to "Check-in feito", and a retry that went looking for the
    // actionable label again would then never find it and fail a check-in
    // that had in fact already landed.
    if (await registered.isVisible().catch(() => false)) return;
    // From the second attempt on, reload before looking again. The card is
    // rendered from three queries (the team, the route, the settings), and a
    // hint purchase or another team's write can leave this page holding a
    // version of them in which `canCheckin` is false — no button at all,
    // rather than a button that fails. Reloading is what a person does, and
    // it is the only thing that clears that state.
    if (attempt++ > 0) {
      await page.reload();
      if (await registered.isVisible().catch(() => false)) return;
    }
    await button.click({ timeout: 5_000 });
    await expect(registered).toBeVisible({ timeout: 5_000 });
  }).toPass({ timeout: 60_000 });
}

/**
 * Walk a team to whichever post the app is currently offering, and check in
 * there by pressing the button.
 *
 * The post is read from the team's own progress rather than chosen by the
 * test, because that is the only post the participant screen will let them
 * check into — `NextCheckpointCard` renders one "próximo posto" and nothing
 * else on the page can register an arrival.
 */
/**
 * The team's own score, read where the team reads it.
 *
 * Anchored on the "Pontos" caption rather than on a class name: the header
 * renders three of these figures side by side (position, points, posts) and
 * only the caption tells them apart.
 */
function ownScore(page: Page) {
  return page.locator('xpath=//p[normalize-space(.)="Pontos"]/preceding-sibling::p[1]');
}

async function walkToPostAndCheckIn(page: Page, target: BuiltPost): Promise<void> {
  // Waits for the app to actually be offering this post before standing at
  // it. Scoring a challenge is what advances a team, and that lands
  // asynchronously — pressing check-in before it does would register at the
  // post the team is already standing on, succeed, and quietly leave the team
  // one post behind for the rest of the phase.
  //
  // "Is the app offering it?" is asked of the app: the riddle for the next
  // post is what the card renders, and it is the only thing the team has to
  // go on.
  await expect(async () => {
    await page.reload();
    await expect(page.getByText(target.clue.slice(0, 30)).first()).toBeVisible({
      timeout: 10_000,
    });
  }).toPass({ timeout: 45_000 });

  await standAt(page.context(), target);
  await page.reload();
  await checkInWithGpsButton(page);
}

/** See master-peddy-tascas-day.spec.ts — the save bar exists only while dirty. */
async function saveSettings(page: Page): Promise<void> {
  const save = page.getByRole("button", { name: "Guardar" });
  await save.click({ timeout: 15_000 });
  await expect(save).toBeHidden({ timeout: 15_000 });
}

test.describe("Peddy paper de Aveiro — a edição que já aconteceu", () => {
  test.setTimeout(900_000);

  test.beforeAll(async () => {
    await waitForApi();
  });

  // ---------------------------------------------------------------------
  // PLANEAMENTO — a folha de planeamento, transcrita para a aplicação
  // ---------------------------------------------------------------------
  test("Planeamento — a organização passa a folha do peddy paper para a app, etapa a etapa", async ({
    browser,
  }) => {
    const cast = await seedPeddyTascasCast({ staffCount: AVEIRO_POSTS.length, guideCount: 2 });
    const { runId } = cast;
    const adminPage = await newAuthedPage(browser, cast.admin.user);

    try {
      // --- The edition ----------------------------------------------------
      const eventName = `Peddy Paper Aveiro ${runId}`;
      await adminPage.goto("/rally/admin?tab=events");
      await adminPage.getByRole("button", { name: "Novo" }).click();
      await adminPage.locator("#ev-name").fill(eventName);
      await adminPage.locator("#ev-type").click();
      await adminPage.getByRole("option", { name: "Peddy-paper" }).click();
      await adminPage.getByRole("button", { name: /^Criar$/ }).click();
      await expect(adminPage.getByText(eventName)).toBeVisible({ timeout: 15_000 });

      const events = await apiCall<{ id: number; name: string; is_current: boolean }[]>(
        "GET",
        "/events",
        { token: cast.admin.user.accessToken },
      );
      const event = events.find((e) => e.name === eventName);
      expect(event).toBeDefined();
      if (!event) throw new Error("unreachable");
      if (!event.is_current) {
        const card = adminPage.locator(".rally-surface", { hasText: eventName });
        await card.getByRole("button", { name: "Tornar atual" }).click();
        await expect(card.getByText("Atual", { exact: true })).toBeVisible({ timeout: 15_000 });
      }

      // --- What the bar screen shows ---------------------------------------
      // A peddy-paper edition bootstraps its standings hidden, which is the
      // right default for a route whose whole point is not knowing where
      // anyone is. This edition ran with a public board, so that is a
      // deliberate switch — and without it the anonymous viewer later in this
      // spec sees an empty page.
      await adminPage.goto("/rally/settings");
      await adminPage.getByRole("button", { name: "Visualização" }).click();
      await adminPage.locator("#show_score_mode").click();
      await adminPage.getByRole("option", { name: "Classificação completa" }).click();
      await saveSettings(adminPage);
      // Stages exist as data whether or not their rules are enforced: with the
      // switch off the whole route runs as one block under
      // checkpoint_order_matters, and the two blocks are just labels. This
      // route is the reason the feature exists — the university posts in
      // order, the ones outside as a set — so it goes on.
      await adminPage.getByRole("button", { name: "Rota" }).click();
      await adminPage.locator("label:has(#route_stages_enabled)").click();
      await saveSettings(adminPage);

      const display = await apiCall<Record<string, unknown>>("GET", "/rally/settings", {
        token: cast.admin.user.accessToken,
      });
      expect(display.show_score_mode).toBe("competitive");
      expect(display.public_access_enabled).toBe(true);
      expect(display.route_stages_enabled).toBe(true);
      expect(display.checkpoint_order_matters).toBe(true);

      // --- The two blocks of the route, before any post ---------------------
      // The checkpoint form only offers an "Etapa" select once stages exist,
      // and says so in its place when none do — assert that, because it is the
      // instruction an organizer actually follows.
      await adminPage.goto("/rally/admin?tab=checkpoints");
      await expect(adminPage.getByText(/Ainda não criaste nenhuma etapa/)).toBeVisible({
        timeout: 15_000,
      });

      for (const stage of AVEIRO_STAGES) {
        await adminPage.getByPlaceholder("Ex: Universidade").fill(`${stage.name} ${runId}`);
        await adminPage.getByRole("button", { name: "Adicionar etapa" }).click();
        await expect(adminPage.getByText(`${stage.name} ${runId}`).first()).toBeVisible({
          timeout: 15_000,
        });
      }

      // Each block's rule, on the stage's own card. "Fora da Uni" is the one
      // that matters: the teams spread out there, and the switch that says so
      // is the difference between a route and a list.
      for (const stage of AVEIRO_STAGES) {
        const card = adminPage.locator("li", { hasText: `${stage.name} ${runId}` }).first();
        const orderSwitch = card.getByRole("switch");
        // Stages are created with order_matters on, so only the free-choice
        // block is clicked — and the other is asserted rather than clicked, so
        // a default that flipped would fail here instead of silently making
        // both blocks the same.
        if (stage.orderMatters) {
          await expect(orderSwitch).toBeChecked();
        } else {
          await card.getByText("Postos desta etapa por ordem").click();
          await expect(orderSwitch).not.toBeChecked({ timeout: 15_000 });
        }
        if (stage.requiredCount != null) {
          const required = card.getByLabel("Quantos postos contam para avançar");
          await required.fill(String(stage.requiredCount));
          // Committed on blur, which is how the field is written.
          await required.blur();
        }
      }

      // --- The posts, three columns each -----------------------------------
      await adminPage.goto("/rally/admin?tab=checkpoints");
      const built: BuiltPost[] = [];
      for (const [index, post] of AVEIRO_POSTS.entries()) {
        const fullName = post.undecided ? `CF DECIDE ${runId}` : `${post.name} ${runId}`;
        const stageIndex = UNIVERSIDADE_POSTS.includes(post) ? 0 : 1;

        await adminPage.getByPlaceholder("Ex: Checkpoint Central").fill(fullName);
        await adminPage.getByPlaceholder("Ex: 40.6405").fill(String(post.latitude));
        await adminPage.getByPlaceholder("Ex: -8.6538").fill(String(post.longitude));
        await adminPage.getByPlaceholder("Ex: 50").fill(String(ARRIVAL_RADIUS_M));
        await adminPage
          .getByPlaceholder("Ex: Onde o rio encontra a ponte de ferro...")
          .fill(post.clue);
        // The two columns of the planning sheet nothing in this suite had
        // ever filled: what the person at the post talks about, and the
        // challenge as it was planned. Neither is ever shown to a team.
        await adminPage
          .getByPlaceholder("Ex: Falar dos diferentes desportos em que se podem inscrever...")
          .fill(post.staffScript);
        await adminPage
          .getByPlaceholder("Ex: Pirâmide humana. Depois, dois shots por equipa...")
          .fill(post.challengeBrief);
        // exact: the stage manager above has its own "Nome da nova etapa" box
        // and per-stage controls whose labels also contain "Etapa". The option
        // label is "{order}. {name}" (CheckpointForm), so pick it by that
        // rather than by position — a reordered select would silently file the
        // post under the wrong block.
        await adminPage
          .getByLabel("Etapa", { exact: true })
          .selectOption({ label: `${stageIndex + 1}. ${AVEIRO_STAGES[stageIndex]!.name} ${runId}` });

        if (post.undecided) {
          // Still being argued over when the sheet was written. A provisional
          // name is a planning signal; a draft is what actually keeps it out
          // of the teams' route.
          //
          // Scoped by `data-admin-search-key`, not by id: controls rendered
          // through shadcn's <FormField> get a *generated* id (":ra:-form-item"
          // and friends), so there is no #is_draft to select — the
          // search key is the only stable hook these rows carry.
          await toggleFormSwitch(adminPage, "checkpoint_provisional");
          await toggleFormSwitch(adminPage, "checkpoint_draft");
        }

        await adminPage.getByRole("button", { name: "Criar Checkpoint" }).click();
        await expect(adminPage.getByText(fullName).first()).toBeVisible({ timeout: 15_000 });
        built.push({ ...post, id: 0, fullName, order: index + 1, activityId: 0 });
      }

      // --- Read the whole plan back --------------------------------------
      // Through GET /checkpoint/admin/route, not GET /checkpoint/: the
      // planning view is the only one that returns drafts, the staff-only
      // columns, and what each post still lacks. It is also, conveniently,
      // exactly the readiness check an organizer does the night before.
      const route = await apiCall<{
        published_count: number;
        draft_count: number;
        incomplete_published_ids: number[];
        checkpoints: {
          id: number;
          name: string;
          order: number;
          clue: string | null;
          staff_script: string | null;
          challenge_brief: string | null;
          stage_id: number | null;
          is_draft: boolean;
          is_placeholder: boolean;
        }[];
      }>("GET", "/checkpoint/admin/route", { token: cast.admin.user.accessToken });

      const withIds: BuiltPost[] = built.map((post) => {
        const row = route.checkpoints.find((c) => c.name === post.fullName);
        expect(row, `${post.fullName} was not created by the form`).toBeDefined();
        if (!row) throw new Error("unreachable");
        // All three columns of the planning sheet survived the round trip.
        expect(row.clue).toBe(post.clue);
        expect(row.staff_script).toBe(post.staffScript);
        expect(row.challenge_brief).toBe(post.challengeBrief);
        expect(row.stage_id, `${post.fullName} is in no stage`).not.toBeNull();
        expect(row.is_draft).toBe(post.undecided === true);
        expect(row.is_placeholder).toBe(post.undecided === true);
        return { ...post, id: row.id, order: row.order, activityId: 0 };
      });

      // Five posts ready to run and one still being argued over.
      expect(route.published_count).toBe(AVEIRO_POSTS.length - 1);
      expect(route.draft_count).toBe(1);
      // Every published post is still incomplete at this point, and correctly
      // so: none of them has a challenge wired up or anyone stationed there.
      // The readiness view exists to say exactly that, and the rest of setup
      // is the work of clearing it.
      expect(new Set(route.incomplete_published_ids)).toEqual(
        new Set(withIds.filter((p) => !p.undecided).map((p) => p.id)),
      );

      // --- The undecided venue is genuinely invisible ---------------------
      // Not just flagged: a draft must not reach a team or a guide at all, its
      // provisional name must not leak as a clue to what is coming, and the
      // two staff-facing columns must be in no participant payload — handing a
      // team the challenge brief before it arrives gives away both the
      // challenge and, often, the place.
      //
      // Field by field, that is
      // `app/tests/api/test_checkpoint_draft.py::TestADraftIsInvisible` —
      // asserted there rather than here because the moment it describes is
      // before any team has logged in, so there is no screen to look at yet.
      // What the day below adds is the half that does have a screen: no team
      // page ever renders a post's staff script, and the guide view does.
      const faina = withIds.find((post) => post.undecided)!;

      // --- CF decide ------------------------------------------------------
      // The venue is settled, so the post gets its real name and goes live.
      // This has to happen now: the backend refuses to change a draft flag
      // once teams have started, which is the whole reason it is a setup step
      // and not something an organizer can fix at 21h.
      await adminPage.goto("/rally/admin?tab=checkpoints");
      const fainaRow = adminPage.getByRole("listitem", {
        name: `Checkpoint ${faina.fullName}, ordem ${faina.order}`,
      });
      // Target the edit button specifically via its icon/aria-label. dispatchEvent
      // because the row is draggable and swallows a synthesized click.
      await fainaRow
        .locator("button:has(svg.lucide-square-pen, svg.lucide-edit, svg.lucide-pencil), button[aria-label*='Editar']")
        .first()
        .dispatchEvent("click");
      await expect(adminPage.getByText("Editar Checkpoint")).toBeVisible({ timeout: 15_000 });

      const decidedName = `${faina.name} ${runId}`;
      await adminPage.getByPlaceholder("Ex: Checkpoint Central").fill(decidedName);
      await toggleFormSwitch(adminPage, "checkpoint_provisional");
      await toggleFormSwitch(adminPage, "checkpoint_draft");
      await adminPage.getByRole("button", { name: "Atualizar Checkpoint" }).click();
      await expect(adminPage.getByText(decidedName).first()).toBeVisible({ timeout: 15_000 });

      const settledRoute = await apiCall<{
        published_count: number;
        draft_count: number;
        checkpoints: { id: number; name: string; order: number; is_draft: boolean }[];
      }>("GET", "/checkpoint/admin/route", { token: cast.admin.user.accessToken });
      expect(settledRoute.draft_count).toBe(0);
      expect(settledRoute.published_count).toBe(AVEIRO_POSTS.length);
      const settledFaina = settledRoute.checkpoints.find((c) => c.id === faina.id);
      expect(settledFaina?.name).toBe(decidedName);
      expect(settledFaina?.is_draft).toBe(false);

      // Published, it takes its place in the route — inside "Fora da Uni",
      // because stages are contiguous blocks of order and the resequencing
      // keeps posts grouped by stage.
      const finalOrders = new Map(
        settledRoute.checkpoints.map((c) => [c.id, c.order] as const),
      );
      const postsWithFinalOrder: BuiltPost[] = withIds.map((post) => ({
        ...post,
        fullName: post.id === faina.id ? decidedName : post.fullName,
        order: finalOrders.get(post.id)!,
      }));
      const universidadeOrders = UNIVERSIDADE_POSTS.map(
        (p) => postsWithFinalOrder.find((b) => b.key === p.key)!.order,
      );
      const foraOrders = FORA_DA_UNI_POSTS.map(
        (p) => postsWithFinalOrder.find((b) => b.key === p.key)!.order,
      );
      expect(Math.max(...universidadeOrders)).toBeLessThan(Math.min(...foraOrders));

      // --- The challenges ---------------------------------------------
      // Four different activity types, because the real plan has four
      // different shapes of challenge: a ball at a goal is pass/fail, the
      // questions in pairs are scored, the pyramid and the line of shots is
      // against the clock, and "mais criativo" cannot be judged at the post
      // at all. Each type renders its own config inputs, so filling them is
      // the only way to catch a form that wires a box to the wrong key.
      await adminPage.goto("/rally/admin?tab=activities");
      for (const post of postsWithFinalOrder) {
        const activity = post.activity;
        await adminPage.getByRole("button", { name: "Nova Atividade" }).click();
        await adminPage.getByPlaceholder("Ex: Cabo de Guerra").fill(`${activity.name} ${runId}`);
        await adminPage.locator("select").first().selectOption({ value: String(post.id) });
        await adminPage.locator("select").nth(1).selectOption({ label: activity.typeLabel });

        for (const [fieldId, value] of Object.entries(activity.configFields)) {
          await adminPage.locator(`#${fieldId}`).fill(String(value));
        }

        for (const [index, counter] of (activity.penaltyCounters ?? []).entries()) {
          await adminPage.getByRole("button", { name: "Adicionar contador" }).click();
          await adminPage.locator(`#penalty-counter-label-${index}`).fill(counter.label);
          await adminPage.locator(`#penalty-counter-points-${index}`).fill(String(counter.points));
        }

        await adminPage.getByRole("button", { name: /^Criar$/ }).click();
        await expect(adminPage.getByText(`${activity.name} ${runId}`)).toBeVisible({
          timeout: 15_000,
        });
      }

      const activities = await apiCall<{
        activities: {
          id: number;
          name: string;
          activity_type: string;
          checkpoint_id: number;
          config: Record<string, unknown>;
        }[];
      }>("GET", "/activities/", { token: cast.admin.user.accessToken });

      const postsWithActivities: BuiltPost[] = postsWithFinalOrder.map((post) => {
        const row = activities.activities.find((a) => a.name === `${post.activity.name} ${runId}`);
        expect(row, `activity for ${post.fullName} was not created`).toBeDefined();
        if (!row) throw new Error("unreachable");
        expect(row.activity_type).toBe(post.activity.apiType);
        expect(row.checkpoint_id).toBe(post.id);
        // Every box the type-specific section rendered reached the config it
        // names — not just the ones that happen to share a default.
        for (const [fieldId, value] of Object.entries(post.activity.configFields)) {
          const configKey = CONFIG_KEY_BY_FIELD_ID[fieldId];
          expect(configKey, `no config key mapped for ${fieldId}`).toBeDefined();
          expect(row.config[configKey!], `${fieldId} did not reach config.${configKey}`).toBe(value);
        }
        const counters = (row.config.penalty_counters ?? []) as { label: string; points: number }[];
        expect(counters.map((c) => c.label)).toEqual(
          (post.activity.penaltyCounters ?? []).map((c) => c.label),
        );
        expect(counters.map((c) => c.points)).toEqual(
          (post.activity.penaltyCounters ?? []).map((c) => c.points),
        );
        return { ...post, activityId: row.id };
      });

      // --- Somebody at every post ----------------------------------------
      // A peddy paper post is not a sign on a wall: the planning sheet's first
      // column is what the person stationed there talks about, so every post
      // gets one — assigned on the page an organizer uses, one row per person.
      await adminPage.goto("/rally/assignment");
      for (const [index, post] of postsWithActivities.entries()) {
        const member = cast.staff[index]!;
        await expect(adminPage.getByText(member.email)).toBeVisible({ timeout: 20_000 });
        // The disposable Postgres accumulates every rally-staff user ever
        // minted, so scope to the row holding this email rather than to the
        // page (see admin-setup.spec.ts).
        const row = adminPage
          .locator("div.rounded-xl")
          .filter({ has: adminPage.getByText(member.email, { exact: false }) });
        await row.getByRole("combobox").click();
        await adminPage.getByRole("option", { name: post.fullName }).click();
        await expect(adminPage.getByText("Atribuição atualizada com sucesso!")).toBeVisible({
          timeout: 20_000,
        });
      }

      // --- The night-before check comes back clean ------------------------
      const ready = await apiCall<{
        published_count: number;
        draft_count: number;
        incomplete_published_ids: number[];
      }>("GET", "/checkpoint/admin/route", { token: cast.admin.user.accessToken });
      expect(ready.draft_count).toBe(0);
      expect(ready.published_count).toBe(AVEIRO_POSTS.length);
      expect(ready.incomplete_published_ids).toEqual([]);

      world = {
        cast,
        eventId: event.id,
        eventName,
        posts: postsWithActivities,
        teams: [],
      };
    } finally {
      await adminPage.context().close();
    }
  });

  // ---------------------------------------------------------------------
  // A SAÍDA — universidade, em ordem, com toda a gente em campo ao mesmo tempo
  // ---------------------------------------------------------------------
  test("A saída — 4 equipas, 2 guias, o staff dos dois postos e o público, todos ao mesmo tempo", async ({
    browser,
  }) => {
    const { cast } = world;
    const aristides = postByKey("aristides");
    const cantina = postByKey("cantina");

    // Teams are created here rather than in planning because on the day the
    // list is still moving — people drop out and sign up at the door.
    // Through the admin form, because on the day the organizer types these in
    // at the door. Both identifiers come from the app itself: the access code
    // off the confirmation modal — the only place the app ever shows one — and
    // the id off the board's own link to the team's page.
    const adminSetupPage = await newAuthedPage(browser, cast.admin.user);
    const teams: BuiltTeam[] = [];
    try {
      await adminSetupPage.goto("/rally/admin?tab=teams");
      for (const label of TEAM_NAMES) {
        const name = `${label} ${cast.runId}`;
        await adminSetupPage.getByPlaceholder("Ex: Equipa Alpha").fill(name);
        await adminSetupPage.getByRole("button", { name: /^Criar Equipa$/ }).click();
        await expect(adminSetupPage.getByText("Equipa Criada!")).toBeVisible({ timeout: 20_000 });
        const accessCode = (
          await adminSetupPage.getByText(/^[A-Z0-9]{4}-[A-Z0-9]{4}$/).innerText()
        ).trim();
        await adminSetupPage.getByRole("button", { name: "Concluir" }).click();
        await expect(adminSetupPage.getByText(name)).toBeVisible({ timeout: 20_000 });
        teams.push({ id: 0, name, accessCode });
      }

      await adminSetupPage.goto("/rally/scoreboard");
      for (const team of teams) {
        const link = adminSetupPage.locator("a", { hasText: team.name }).first();
        await expect(link).toBeVisible({ timeout: 30_000 });
        const href = await link.getAttribute("href");
        const id = /\/teams\/(\d+)/.exec(href ?? "");
        expect(id, `no team page link for ${team.name}`).not.toBeNull();
        teams[teams.indexOf(team)] = { ...team, id: Number(id![1]) };
      }

      // Guides walk with the first two teams — assigned on the page that
      // exists for exactly that, one row per guide.
      await adminSetupPage.goto("/rally/guide-assignment");
      for (const [index, guide] of cast.guides.entries()) {
        await expect(adminSetupPage.getByText(guide.email)).toBeVisible({ timeout: 20_000 });
        const row = adminSetupPage
          .locator("div.rounded-xl")
          .filter({ has: adminSetupPage.getByText(guide.email, { exact: false }) });
        await row.getByRole("combobox").click();
        await adminSetupPage.getByRole("option", { name: teams[index]!.name }).click();
        await expect(adminSetupPage.getByText("Atribuição atualizada com sucesso!")).toBeVisible({
          timeout: 20_000,
        });
      }
    } finally {
      await adminSetupPage.context().close();
    }
    world = { ...world, teams };

    const publicPage = await newPage(browser);
    const guidePages = await Promise.all(
      cast.guides.map((guide) => newAuthedPage(browser, guide.user)),
    );
    const staffAristides = await newAuthedPage(browser, cast.staff[0]!.user);
    const staffCantina = await newAuthedPage(browser, cast.staff[1]!.user);
    const teamPages = await Promise.all(teams.map(() => newPage(browser)));

    try {
      for (const page of teamPages) {
        await standAt(page.context(), aristides);
      }

      // Everything opens at once — the board in the bar, both guides, both
      // staffed posts and all four teams, two of them signing in by hand.
      // This is the part the brief is about: on a real day nobody waits their
      // turn.
      await Promise.all([
        (async () => {
          await publicPage.goto("/rally/scoreboard");
          await expect(publicPage.getByText(teams[0]!.name)).toBeVisible({ timeout: 30_000 });
        })(),
        ...guidePages.map(async (page) => {
          await page.goto("/rally/guide");
          await expect(page.getByText("Postos — Visão do Guia")).toBeVisible({ timeout: 30_000 });
        }),
        (async () => {
          await staffAristides.goto("/rally/staff-evaluation");
        })(),
        (async () => {
          await staffCantina.goto("/rally/staff-evaluation");
        })(),
        ...teamPages.map(async (page, index) => {
          await teamLoginThroughForm(page, teams[index]!.accessCode);
          await expect(page.getByText("Enigma")).toBeVisible({ timeout: 30_000 });
        }),
      ]);

      // --- What the guide is holding, on screen -----------------------------
      // The planning sheet's other two columns, rendered for the person
      // standing at the post: "Assuntos a abordar" and "Desafio". Asserted
      // here rather than only in the payload, because the whole reason those
      // fields exist is that somebody reads them off a phone at the post.
      const guideCard = guidePages[0]!.locator("section, div").filter({
        hasText: aristides.staffScript.slice(0, 40),
      });
      await expect(guidePages[0]!.getByText("Assuntos a abordar")).toBeVisible({ timeout: 30_000 });
      await expect(guideCard.first()).toBeVisible();
      await expect(guidePages[0]!.getByText("Desafio", { exact: true })).toBeVisible();
      await expect(
        guidePages[0]!.getByText(aristides.challengeBrief.slice(0, 40), { exact: false }).first(),
      ).toBeVisible();
      // And the riddle the team was given, so the guide knows what they are
      // stuck on.
      await expect(guidePages[0]!.getByText("Enigma dado à equipa")).toBeVisible();

      // The first clue is the one the sheet says it is, and the post's real
      // name is nowhere near a participant — on all four phones, which is
      // where it would leak.
      for (const page of teamPages) {
        await expect(page.getByText(aristides.clue.slice(0, 30)).first()).toBeVisible({
          timeout: 30_000,
        });
        expect(await page.content()).not.toContain(aristides.name);
      }

      // The guide, standing at the post, is holding the columns the team never
      // sees: what to talk about, and the challenge as it was planned. Both
      // are already on screen from the assertions above — the point here is
      // that the same two columns are on the *guide's* page and on no team's.
      for (const page of teamPages) {
        const html = await page.content();
        expect(html).not.toContain(aristides.staffScript);
        expect(html).not.toContain(aristides.challengeBrief);
      }

      // All four teams reach the first post at once — each pressing the
      // check-in button on its own phone, which is the participant's single
      // most-used control and the only proof of arrival a redacted route
      // leaves them.
      await Promise.all(teamPages.map((page) => checkInWithGpsButton(page)));

      // Proven from the guide's screen rather than from the team's own: the
      // panel at the post lists who has turned up, which is what the person
      // standing there actually reads. Note this is *arrival*, not progress —
      // a post with a challenge is not resolved until it is scored, so the
      // teams are here without having advanced, which is exactly the state
      // the staff member is about to work through.
      await guidePages[0]!.reload();
      for (const team of teams) {
        await expect(
          guidePages[0]!.getByText(team.name).first(),
          `${team.name} is not listed at the post`,
        ).toBeVisible({ timeout: 30_000 });
      }

      // --- The ball at the goal, scored with its miss counter --------------
      // "Encher o copo a cada um, cada falha tem de beber" is a count, not a
      // yes/no — so the Sim/Não form carries the "Falha na baliza" counter the
      // planning phase configured, and every miss costs its points.
      await staffAristides.reload();
      const misses = [0, 1, 2, 3];
      for (const [index, team] of teams.entries()) {
        await evaluateBoolean(staffAristides, team.name, {
          success: true,
          counterLabel: aristides.activity.penaltyCounters![0]!.label,
          count: misses[index]!,
        });
      }

      // The arithmetic the counter promises: success points minus one
      // deduction per miss, and no team's score below zero.
      const successPoints = aristides.activity.configFields["config-bool-success"]!;
      const perMiss = aristides.activity.penaltyCounters![0]!.points;
      for (const [index, page] of teamPages.entries()) {
        // Read where the team reads it: the "Pontos" figure on its own
        // screen, which is the number that decides whether anyone believes
        // the counter did what the form said it would.
        await expect(async () => {
          await page.reload();
          await expect(ownScore(page)).toHaveText(
            String(Math.max(0, successPoints - misses[index]! * perMiss)),
            { timeout: 10_000 },
          );
        }, `${teams[index]!.name} scored the ball challenge wrong`).toPass({ timeout: 45_000 });
      }

      // --- On to the cantina, in order ------------------------------------
      // A team that wanders off to a post in the next block is a real thing
      // on a real day — someone recognises a bar from the list and walks in.
      // The rule is that the arrival is *recorded* (standing somewhere is a
      // fact) but must not move the team on, because "Universidade" runs in
      // order and its posts are not done: progress is gated, arrivals are
      // not, and conflating the two is the easy mistake to make here.
      //
      // It is not asserted from this spec, because there is no way to express
      // it by clicking: the participant screen offers exactly one "próximo
      // posto" and no control that names another. It is asserted directly in
      // `app/tests/api/test_route_stage.py::test_ordered_stage_still_requires_sequence`,
      // where the arrival can be posted at the post it names.

      // On to the cantina — the teams walk there and press the button again,
      // rather than the test posting an arrival on their behalf.
      await Promise.all(
        teamPages.map(async (page) => {
          await standAt(page.context(), cantina);
          await page.reload();
          // .first(): the clue legitimately appears twice on this screen — in
          // the riddle panel and again in the route list below it.
          await expect(page.getByText(cantina.clue.slice(0, 30)).first()).toBeVisible({
            timeout: 30_000,
          });
          await checkInWithGpsButton(page);
        }),
      );
      await staffCantina.reload();
      // Questions in pairs, scored out of the max the form was configured with,
      // and a penalty for each pair that got it wrong.
      const scores = [80, 60, 40, 20];
      const penalties = [0, 1, 0, 2];
      for (const [index, team] of teams.entries()) {
        await evaluateScoreBased(staffCantina, team.name, {
          score: scores[index]!,
          counterLabel: cantina.activity.penaltyCounters![0]!.label,
          count: penalties[index]!,
        });
      }

      // The public board, open since before anyone set off, has every one of
      // those writes — through SSE, with no reload. Every team, not just one:
      // a board that updated for the first team and stalled for the rest
      // would satisfy a single-team check.
      for (const team of teams) {
        await expect(
          publicPage.locator("a", { hasText: team.name }).first().getByText(/pts/),
        ).not.toHaveText("0 pts", { timeout: 60_000 });
      }

    } finally {
      await Promise.all([
        publicPage.context().close(),
        staffAristides.context().close(),
        staffCantina.context().close(),
        ...guidePages.map((page) => page.context().close()),
        ...teamPages.map((page) => page.context().close()),
      ]);
    }
  });

  // ---------------------------------------------------------------------
  // FORA DA UNI — bloco à escolha, e o que só se julga no fim
  // ---------------------------------------------------------------------
  test("Fora da uni — as equipas espalham-se pelos postos à escolha, e o mais criativo só se decide no fim", async ({
    browser,
  }) => {
    const { cast, teams } = world;
    const faina = postByKey("faina");
    const museu = postByKey("museu");
    const ponte = postByKey("ponte");
    const praca = postByKey("praca");

    const staffFaina = await newAuthedPage(browser, cast.staff[2]!.user);
    const staffMuseu = await newAuthedPage(browser, cast.staff[3]!.user);
    const adminPage = await newAuthedPage(browser, cast.admin.user);
    // Four phones, four codes typed in — the same way the morning started,
    // because a phase that resumed from a seeded session would be testing a
    // state no participant can reach.
    const teamPages: Page[] = [];
    for (const team of teams) {
      const page = await newPage(browser);
      await teamLoginThroughForm(page, team.accessCode);
      teamPages.push(page);
    }

    try {
      // --- The block the teams work through -------------------------------
      // "Fora da Uni" runs with order_matters off, so the backend takes a team
      // at any of its posts in any order — and now the team's own screen says
      // so. The server marks every open post `is_reachable`, and the route
      // list puts a check-in button on each one, so the block is a real choice
      // rather than whichever post the app happened to name as next.
      //
      // Asserted below on the participant screen. The teams are then walked in
      // the app's own order, which is *not* the sheet's: the Faina was the
      // undecided venue, and publishing a draft appends it to the end of its
      // stage.
      // The choice, on the team's phone: more than one post in this block
      // offers a check-in button at the same time. Under the university
      // block's ordered rule there is exactly one, which is the difference
      // stages exist to express — and which the team could not see at all
      // until the server started marking reachability.
      await teamPages[0]!.goto("/rally/team-progress");
      await expect
        .poll(
          async () => teamPages[0]!.getByRole("button", { name: "Check-in GPS aqui" }).count(),
          { timeout: 30_000 },
        )
        .toBeGreaterThan(0);

      const blockOrder = [museu, ponte, praca, faina];
      expect(
        blockOrder.map((post) => post.order),
        "the block is not in the order this phase assumes",
      ).toEqual([...blockOrder.map((post) => post.order)].sort((a, b) => a - b));

      // --- Recriar uma obra, pontuada à mão -------------------------------
      await Promise.all(
        teamPages.map((page) => walkToPostAndCheckIn(page, museu)),
      );
      await staffMuseu.goto("/rally/staff-evaluation");
      const museuPoints = [55, 40, 30, 20];
      for (const [index, team] of teams.entries()) {
        await evaluateGeneral(staffMuseu, team.name, museuPoints[index]!);
      }

      // --- What nobody at the post can decide -----------------------------
      // "Mais criativo recebe uma salva de palmas" is not a score a staff
      // member can give on the spot: it only means anything once every team
      // has had its turn. So the post captures the attempt and the judging
      // happens afterwards — which is what a deferred-judged activity is.
      await Promise.all(teamPages.map((page) => walkToPostAndCheckIn(page, ponte)));

      // The one call in this phase that is not a click, and the reason is the
      // stack rather than the app: `DeferredJudgedForm` refuses to submit
      // without at least one photo, and photos go to R2, which the smoke
      // stack does not run (see this directory's README, "Anything that needs
      // object storage"). Everything the *judge* does below is on screen.
      for (const team of teams) {
        const captured = await fetch(
          `${API_V1}/activities/deferred/${ponte.activityId}/capture?team_id=${team.id}`,
          {
            method: "POST",
            headers: { Authorization: `Bearer ${cast.staff[4]!.user.accessToken}` },
            body: new FormData(),
          },
        );
        expect(captured.status, `capture for ${team.name} failed`).toBe(201);
      }

      // Each team's total before the judging, read off its own screen: what
      // the judge's ordering is worth is the difference these numbers move by.
      const before: number[] = [];
      for (const page of teamPages) {
        await page.reload();
        before.push(Number(await ownScore(page).innerText()));
      }

      // --- The judge decides, at the end, in one sitting -------------------
      // On the Julgamento tab: a list of this activity's captures, arrows to
      // order them, one confirm. Nothing is scored until that press — which
      // is the whole point of deferring it, and is visible here as four
      // captures sitting in the queue with the totals above unmoved.
      await adminPage.goto("/rally/admin?tab=judging");
      // Scoped to this run's activity: the shared disposable Postgres keeps
      // every previous run's unjudged captures, and the tab groups them by
      // activity. Walk up from one of this run's own team rows to the nearest
      // ancestor that also holds a "Confirmar ordenação" — that is this
      // activity's card. `normalize-space(.)` rather than `text()`, because
      // React renders `Equipa #{id}` as two text nodes; `ancestor::li`,
      // because the group root is an <li> and the rows inside it are too — a
      // row holds no confirm button, so the predicate picks the card.
      const ponteGroup = adminPage.locator(
        `xpath=//*[normalize-space(.)="Equipa #${teams[0]!.id}"]` +
          `/ancestor::li[.//button[normalize-space()="Confirmar ordenação"]][1]`,
      );
      await expect(ponteGroup.getByText(`Equipa #${teams[0]!.id}`)).toBeVisible({ timeout: 30_000 });
      for (const team of teams) {
        await expect(ponteGroup.getByText(`Equipa #${team.id}`)).toBeVisible();
      }

      // The speech the organizers liked best goes to the top, by pressing the
      // arrow the judge would press.
      const winnerUp = ponteGroup.getByRole("button", {
        name: `Subir equipa #${teams[2]!.id}`,
      });
      // Up as far as it goes: the button disables itself at the top, which is
      // also the signal to stop.
      for (let i = 0; i < teams.length - 1; i++) {
        if (await winnerUp.isDisabled()) break;
        await winnerUp.click();
      }
      // And the one they liked least to the bottom.
      const lastDown = ponteGroup.getByRole("button", { name: `Descer equipa #${teams[1]!.id}` });
      for (let i = 0; i < teams.length - 1; i++) {
        if (await lastDown.isDisabled()) break;
        await lastDown.click();
      }
      await ponteGroup.getByRole("button", { name: "Confirmar ordenação" }).click();
      // The queue empties: confirming an order judges every capture in it.
      await expect(ponteGroup).toHaveCount(0, { timeout: 30_000 });

      // What the ordering was worth, measured where it lands — on each team's
      // own total. First place takes the activity's configured maximum, last
      // its minimum, and the order the judge chose is the order of the gains.
      const gained: number[] = [];
      for (const [index, page] of teamPages.entries()) {
        await expect(async () => {
          await page.reload();
          await expect(ownScore(page)).not.toHaveText(String(before[index]!), { timeout: 10_000 });
        }).toPass({ timeout: 45_000 });
        gained.push(Number(await ownScore(page).innerText()) - before[index]!);
      }
      expect(gained[2]).toBe(ponte.activity.configFields["config-dj-max-points"]);
      expect(gained[1]).toBe(ponte.activity.configFields["config-dj-min-points"]);
      expect(gained[2]!).toBeGreaterThan(gained[0]!);
      expect(gained[0]!).toBeGreaterThan(gained[3]!);

      // --- The Titanic scene, captured the same way -------------------------
      await Promise.all(
        teamPages.map((page) => walkToPostAndCheckIn(page, praca)),
      );
      for (const team of teams) {
        const captured = await fetch(
          `${API_V1}/activities/deferred/${praca.activityId}/capture?team_id=${team.id}`,
          {
            method: "POST",
            headers: { Authorization: `Bearer ${cast.staff[5]!.user.accessToken}` },
            body: new FormData(),
          },
        );
        expect(captured.status, `praça capture for ${team.name} failed`).toBe(201);
      }
      // Judged the same way, on the same tab — this time the judge accepts the
      // order as it stands, which is the other half of that screen: confirming
      // is a decision even when nothing was moved.
      await adminPage.goto("/rally/admin?tab=judging");
      const pracaGroup = adminPage.locator(
        `xpath=//*[normalize-space(.)="Equipa #${teams[0]!.id}"]` +
          `/ancestor::li[.//button[normalize-space()="Confirmar ordenação"]][1]`,
      );
      await expect(pracaGroup.getByText(`Equipa #${teams[0]!.id}`)).toBeVisible({ timeout: 30_000 });
      await pracaGroup.getByRole("button", { name: "Confirmar ordenação" }).click();
      await expect(pracaGroup).toHaveCount(0, { timeout: 30_000 });

      // --- The pyramid and the line of shots, against the clock ------------
      // "Sem reação em menos de 3 min": scored on the seconds it took, ranked
      // against the other teams. Last in the block, because the venue for it
      // was the one still undecided when the sheet was written.
      await Promise.all(
        teamPages.map((page) => walkToPostAndCheckIn(page, faina)),
      );
      const beforeFaina: number[] = [];
      for (const page of teamPages) {
        await page.reload();
        beforeFaina.push(Number(await ownScore(page).innerText()));
      }

      await staffFaina.goto("/rally/staff-evaluation");
      const seconds = [95, 140, 172, 178];
      for (const [index, team] of teams.entries()) {
        await evaluateTimeBased(staffFaina, team.name, seconds[index]!);
      }

      // Fastest gets the configured maximum, slowest the minimum — measured
      // where a team would notice it, as the jump in its own score. A
      // time-based activity ranks the teams against each other, so the last
      // submission can move an earlier team's number too; the reads below all
      // happen after the last one lands.
      const fainaGain: number[] = [];
      for (const [index, page] of teamPages.entries()) {
        await expect(async () => {
          await page.reload();
          await expect(ownScore(page)).not.toHaveText(String(beforeFaina[index]!), {
            timeout: 10_000,
          });
        }).toPass({ timeout: 45_000 });
        fainaGain.push(Number(await ownScore(page).innerText()) - beforeFaina[index]!);
      }
      expect(fainaGain[0]).toBe(faina.activity.configFields["config-tb-max-points"]);
      expect(fainaGain[3]).toBe(faina.activity.configFields["config-tb-min-points"]);
      expect(fainaGain[0]!).toBeGreaterThan(fainaGain[1]!);

      // --- The route is finished ------------------------------------------
      // Every post of both blocks is done, so the app stops handing out a next
      // one — asserted on the participant's own screen, which is where a team
      // finds out the route is over.
      // The team's own screen says so. This is the assertion that found
      // the bug where it could not: `current_checkpoint_number` used to clamp
      // to the last post's order when everything was done, so the client kept
      // finding a "next" post and a finished team was shown the post it had
      // just completed, forever. The API said 6 of 6 and was right, which is
      // why only walking a participant screen to the end of a route caught it.
      //
      // Reloaded inside the retry: the last score lands asynchronously.
      await expect(async () => {
        await teamPages[0]!.goto("/rally/team-progress");
        await expect(teamPages[0]!.getByText("Chegaram ao fim!")).toBeVisible({ timeout: 5_000 });
      }).toPass({ timeout: 60_000 });

      // --- Standings --------------------------------------------------------
      // The public board agrees with each team's own total — the two screens
      // an organizer gets asked about, showing the same number.
      //
      // Compared after rounding, and only here: `update_team_scores` stores
      // `Team.total` as a rounded integer while the live ranking keeps the
      // float, and a time-based activity ranks teams linearly between its min
      // and max, so this route produces genuinely fractional scores (378.33
      // stored as 378). The two numbers are the same score to within that
      // rounding, which is what this asserts — an exact match would be
      // asserting that no activity type ever yields a fraction.
      const boardPage = await newPage(browser);
      try {
        await boardPage.goto("/rally/scoreboard");
        await expect(boardPage.getByText(teams[0]!.name)).toBeVisible({ timeout: 30_000 });
        for (const [index, page] of teamPages.entries()) {
          await page.reload();
          const own = Number(await ownScore(page).innerText());
          await expect(async () => {
            await boardPage.reload();
            const card = boardPage.locator("a", { hasText: teams[index]!.name }).first();
            const shown = /(-?\d+)\s*pts/.exec(await card.innerText());
            expect(shown, `no points on the board for ${teams[index]!.name}`).not.toBeNull();
            // Within a point, for the rounding reason above.
            expect(Math.abs(Number(shown![1]) - own)).toBeLessThanOrEqual(1);
          }).toPass({ timeout: 30_000 });
        }
      } finally {
        await boardPage.context().close();
      }

      // And the day is in the record: the organizer's Auditoria tab carries
      // this edition, which is what they go back to when a team disputes a
      // score a week later.
      await adminPage.goto("/rally/admin?tab=audit");
      await expect(adminPage.getByText("Sem registos para os filtros atuais.")).toHaveCount(0, {
        timeout: 30_000,
      });
      await expect(adminPage.locator("div.rounded-lg").first()).toBeVisible();

      // The exports an organizer actually sends round afterwards, from the
      // buttons on the Edições tab.
      await adminPage.goto("/rally/admin?tab=events");
      const eventCard = adminPage.locator(".rally-surface", { hasText: world.eventName }).first();
      for (const [button, extension] of [
        ["Exportar resultados", ".xlsx"],
        ["Relatório (PDF)", ".pdf"],
      ] as const) {
        const downloadPromise = adminPage.waitForEvent("download", { timeout: 60_000 });
        await eventCard.getByRole("button", { name: button }).click();
        const download = await downloadPromise;
        expect(download.suggestedFilename()).toContain(extension);
        const downloadedPath = await download.path();
        expect(downloadedPath, `${button} produced no file`).toBeTruthy();
        expect(fs.statSync(downloadedPath!).size).toBeGreaterThan(0);
      }
    } finally {
      await Promise.all([
        staffFaina.context().close(),
        staffMuseu.context().close(),
        adminPage.context().close(),
        ...teamPages.map((page) => page.context().close()),
      ]);
    }
  });
});
